// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBDT6bvRrROM4fP39uhot28Vhu0gOERcZE',
    appId: '1:237602416648:web:65775f0443c773e73bc9bd',
    messagingSenderId: '237602416648',
    projectId: 'attendancepro-1a8e4',
    authDomain: 'attendancepro-1a8e4.firebaseapp.com',
    storageBucket: 'attendancepro-1a8e4.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD5lP1JwnDC2GJww-PP3mTQXh-iIRXssnY',
    appId: '1:237602416648:android:38a751c555d5feab3bc9bd',
    messagingSenderId: '237602416648',
    projectId: 'attendancepro-1a8e4',
    storageBucket: 'attendancepro-1a8e4.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAdxm9ozbgSBG-OEbYruWnoW1DfeB62bWk',
    appId: '1:237602416648:ios:1b87000e033cacf13bc9bd',
    messagingSenderId: '237602416648',
    projectId: 'attendancepro-1a8e4',
    storageBucket: 'attendancepro-1a8e4.firebasestorage.app',
    iosBundleId: 'com.example.attendancepro',
  );
}
