abstract final class AppString {
  AppString._();

  static const String fontFamily = 'Inter';
  static const String appName = 'AttendancePro';
  static const String timePlaceholder = '--:--';
  static const String doubleDashPlaceholder = '--';
  static const String timeInputHint = 'HH:MM';
  static const String zeroInputHint = '0';
  static const String zeroDecimalInputHint = '0.00';
  static const String zeroMinutesLabel = '0 min';
  static const String sixtyMinutesLabel = '60 min (1h)';
  static const String minutesSuffix = 'min';
  static const String minuteAbbreviation = 'm';
  static const String hourAbbreviation = 'h';
  static const String amLabel = 'AM';
  static const String pmLabel = 'PM';
  static const String contractNameHint = 'Water melon, Orange';
  static const String contractRateHint = 'Price Per 100 Bunches';
  static const String contractUnitHint = 'per beans';
  static const String euroPrefix = '€ ';
  static const String emDash = '—';
  static const String fallbackContractItemWatermelonTitle = 'Watermelon';
  static const String fallbackContractItemWatermelonPrice =
      'Price per Crate (€)';
  static const String fallbackContractItemTitle = 'Ravanello (10 qty)';
  static const String fallbackContractItemRavanello15Title =
      'Ravanello (15 qty)';
  static const String fallbackContractItemRavanello18Title =
      'Ravanello (18 qty)';
  static const String fallbackContractItemRavanello18AltTitle =
      'Ravanello (18 qty)';
  static const String fallbackContractItemRavanelloPrice =
      'Price Per 100 Bunches';
  static const String fallbackContractItemPriceLow = 'Price Per 100 Bunches';
  static const String fallbackContractItemPriceHigh = 'Price Per 100 Bunches';
  static const String fallbackContractItemCarrotTitle = 'Carrot';
  static const String fallbackContractItemCarrotPrice =
      'Price per Crate (€)';
  static const String fallbackContractItemOrangeTitle = 'Orange';
  static const String fallbackContractItemOrangePrice =
      'Price per Crate (€)';
  static const String fallbackSummaryHours = '156.5h';
  static const String fallbackSummarySalary = '€1950';
  static const String fallbackSummaryHourly = '€956';
  static const String fallbackSummaryContract = '€994';
  static const List<String> shortMonthAbbreviations = <String>[
    'Jan',
    'Feb',
    'Mar',
    'Apr',
    'May',
    'Jun',
    'Jul',
    'Aug',
    'Sep',
    'Oct',
    'Nov',
    'Dec',
  ];
  static const List<String> fullMonthNames = <String>[
    'January',
    'February',
    'March',
    'April',
    'May',
    'June',
    'July',
    'August',
    'September',
    'October',
    'November',
    'December',
  ];

  static const Map<String, Map<String, String>> localizedValues = {
    'en': {
      'appTitle': 'AttendancePro',
      'drawerUserName': 'John Snow',
      'drawerUserPhone': '+39-319-055-5550',
      'dashboardLabel': 'Works List',
      'homeBannerTitle': 'Track Attendance Smarter',
      'homeBannerSubtitle':
          'Manage your shifts, track hours, and stay organized every day.',
      'adPlaceholderTitle': 'Ad placement coming soon',
      'adPlaceholderSubtitle':
          'We will show relevant offers here shortly. Stay tuned!',
      'addNewWorkLabel': 'Add New Work',
      'selectWorkTitle': 'Select Work',
      'workSelectionSubtitle':
          'Choose the work you want to view reports for.',
      'confirmSelectionButton': 'Confirm',
      'workSelectionHourSuffix': '/hour',
      'attendanceHistoryLabel': 'Attendance History',
      'attendanceHistoryMonthLabel': 'Select month',
      'attendanceHistorySummaryTitle': 'This month so far',
      'attendanceHistoryWorkedDaysLabel': 'Worked Days',
      'attendanceHistoryLeaveDaysLabel': 'Leaves',
      'attendanceHistoryOvertimeLabel': 'Overtime',
      'attendanceHistoryTimelineTitle': 'Daily timeline',
      'attendanceHistoryNoEntriesLabel': 'No attendance records yet.',
      'attendanceHistoryLoadFailedMessage':
          'Unable to load attendance history. Please try again.',
      'attendanceHistoryHourlyEntry': 'Hourly',
      'attendanceHistoryContractEntry': 'Contract',
      'attendanceHistoryLeaveEntry': 'Leave',
      'attendanceHistoryPendingTitle': 'Pending attendance entries',
      'attendanceHistoryPendingDescription':
          'Complete previous days before marking today as present.',
      'attendanceHistoryResolveButton': 'Resolve now',
      'attendanceHistoryAllCaughtUp': 'You are all caught up!',
      'attendanceHistoryAllCaughtUpDescription':
          'All past attendance entries are completed.',
      'attendanceHistoryAllWorks': 'All Works',
      'attendanceHistoryOvertimeEntryLabel': 'Overtime',
      'attendanceHistoryLoggedHoursLabel': 'Logged Hours',
      'attendanceHistoryReasonLabel': 'Reason',
      'contractReportDownloadLabel': 'Download contract report (PDF)',
      'historyReportDownloadLabel': 'Download attendance history (PDF)',
      'reportDownloadNoEntriesMessage':
          'No records are available for the selected view.',
      'reportDownloadSuccessMessage': 'PDF saved to {path}',
      'reportDownloadFailedMessage':
          'Unable to generate PDF report. Please try again.',
      'contractWorkLabel': 'Contract Work',
      'contractWorkActiveRatesTitle': 'Active contract rates',
      'contractWorkDefaultTypesTitle': 'Contract types',
      'contractWorkRecentEntriesTitle': 'Recent contract entries',
      'contractWorkRatesNote': 'Rates apply to future entries only.',
      'contractWorkAddTypeTitle': 'Add contract type',
      'contractWorkEditTypeTitle': 'Update contract type',
      'contractWorkSetupSubtitle': 'Select contract work types and set rates',
      'contractWorkContractTypeLabel': 'Contract type',
      'contractWorkContractTypeHint': 'Select contract type',
      'contractWorkPricePerCrateLabel': 'Price per crate',
      'contractWorkSaveAllButton': 'Save all contract works',
      'contractWorkNameLabel': 'Contract name',
      'contractWorkSelectWorkHint': 'Select Work',
      'contractWorkCustomOption': 'Custom Work',
      'contractWorkRateLabel': 'Rate',
      'contractWorkRateHint': 'Enter rate',
      'contractWorkPricePerBinHint': 'Price Per 1 Bin',
      'contractWorkPricePerCrateHint': 'Price Per 1 Crate',
      'contractWorkPricePerBunchesHint': 'Price Per 100 Bunches',
      'contractWorkUnitLabel': 'Unit label',
      'contractWorkSubtypeLabel': 'Type',
      'contractWorkSubtypeHint': 'Select type',
      'contractWorkSubtypeCustomOption': 'Custom subtype',
      'contractWorkSubtypeCustomLabel': 'Custom subtype',
      'contractWorkSubtypeRequiredMessage': 'Please select a type.',
      'contractWorkTypeLabel': 'Type',
      'contractWorkTypeHint': 'Select type',
      'contractWorkTypeFixedOption': 'Fixed',
      'contractWorkTypeBundleOption': 'Bundle',
      'contractWorkRoleLabel': 'Role',
      'contractWorkRoleHint': 'Select role',
      'contractWorkRoleRequiredMessage': 'Please select a role.',
      'contractWorkUnitsLabel': 'Units',
      'contractWorkUnitsHint': 'Enter units',
      'contractWorkRateRequiredMessage': 'Please enter a valid rate.',
      'contractWorkNameRequiredMessage': 'Please select or enter a work name.',
      'contractWorkTypeSavedMessage': 'Contract type saved.',
      'contractWorkDeleteConfirmationTitle': 'Delete contract type',
      'contractWorkDeleteConfirmationMessage':
          'Are you sure you want to delete this contract type?',
      'contractWorkDeleteButton': 'Delete',
      'contractWorkTypeDeletedMessage': 'Contract type deleted.',
      'contractWorkTypeDeleteFailedMessage':
          'Unable to delete contract type. Please try again.',
      'contractWorkNoEntriesLabel': 'No contract entries recorded yet.',
      'contractWorkAllTypesAddedMessage':
          'All contract work types are already added.',
      'contractWorkLastUpdatedLabel': 'Last updated',
      'contractWorkEditRateButton': 'Update rate',
      'contractWorkActiveTypesLabel': 'Active types',
      'contractWorkTotalUnitsLabel': 'Total units',
      'contractWorkTotalSalaryLabel': 'Total salary',
      'contractWorkDefaultTag': 'Default',
      'contractWorkUnitFallback': 'per unit',
      'contractWorkCloseSheetLabel': 'Close contract type details',
      'profileLabel': 'Profile',
      'profileTitle': 'Edit Profile',
      'profileNameLabel': 'Full name',
      'profileNameHint': 'Enter your name',
      'profileUsernameLabel': 'Username',
      'profileUsernameHint': 'Enter your username',
      'profilePhoneLabel': 'Phone number',
      'profilePhoneHint': 'Enter your phone number',
      'profileCountryCodeLabel': 'Country code',
      'profileCountryCodeHint': 'Enter country code (e.g. +91)',
      'profileLanguageLabel': 'Preferred language',
      'profileSaveButton': 'Save changes',
      'profileUpdateSuccess': 'Profile updated successfully.',
      'profileUpdateFailed': 'Unable to update profile. Please try again.',
      'profileAuthRequired': 'Please log in again to update your profile.',
      'profileValidationName': 'Please enter your name.',
      'profileValidationUsername': 'Please enter your username.',
      'profileValidationPhone': 'Please enter your phone number.',
      'profileValidationCountryCode': 'Please enter your country code.',
      'profileValidationLanguage': 'Please select a language.',
      'profileLoadingFailed': 'Unable to load profile details.',
      'changeLanguageLabel': 'Change Language',
      'helpSupportLabel': 'Help & Support',
      'helpSupportTitle': 'How can we help you today?',
      'helpSupportSubtitle': 'Find quick answers or reach our support team.',
      'helpSupportQuickActionsTitle': 'Quick assistance',
      'helpSupportFaqsLabel': 'FAQs',
      'helpSupportFaqsSubtitle': 'Browse common questions',
      'helpSupportGuidesLabel': 'Getting Started',
      'helpSupportGuidesSubtitle': 'Step-by-step tutorials',
      'helpSupportReportIssueLabel': 'Report an Issue',
      'helpSupportReportIssueSubtitle': 'Let us know what went wrong',
      'helpSupportContactTitle': 'Contact options',
      'helpSupportEmailLabel': 'Email Us',
      'helpSupportEmailValue': 'support@attendancepro.app',
      'helpSupportEmailButton': 'Send email',
      'helpSupportPhoneLabel': 'Call Us',
      'helpSupportPhoneValue': '+91 9876543210',
      'helpSupportCallButton': 'Call now',
      'helpSupportChatLabel': 'Live Chat',
      'helpSupportChatSubtitle': 'Available Mon-Fri, 9am - 6pm',
      'helpSupportChatButton': 'Start chat',
      'helpSupportHoursLabel': 'Support hours',
      'helpSupportHoursValue': 'Mon - Fri, 9 AM - 6 PM (GMT)',
      'helpSupportResponseTimeLabel': 'Average response time',
      'helpSupportResponseTimeValue': 'Under 24 hours',
      'helpSupportAdditionalInfoTitle': 'Additional information',
      'helpSupportLastUpdatedLabel': 'Last updated',
      'helpSupportLastUpdatedValue': 'October 2025',
      'helpSupportPolicyLabel': 'Support policy',
      'helpSupportPolicyValue': 'We follow the AttendancePro customer care standards.',
      'helpSupportLaunchFailed': 'Unable to open the requested application.',
      'helpSupportComingSoon': 'This section will be available soon.',
      'deleteAccountLabel': 'Delete Account',
      'logoutLabel': 'Logout',
      'reportsSummaryLabel': 'Reports & Summary',
      'reportsSummaryMonth': 'October 2025',
      'reportsCombinedSalaryTitle': 'Total Combined Salary',
      'reportsHoursWorkedSuffix': 'hours worked',
      'reportsUnitsCompletedSuffix': 'units completed',
      'reportsHourlyWorkSummaryTitle': 'Hourly Work Summary',
      'reportsWorkingDaysLabel': 'Working Days',
      'reportsAverageHoursPerDayLabel': 'Average Hours/Day',
      'reportsLastPayoutLabel': 'Last Payout',
      'reportsTotalUnitsLabel': 'Total Units',
      'reportsContractSalaryLabel': 'Contract Salary',
      'reportsBreakdownSuffix': 'Breakdown',
      'reportsMonthlySectionTitle': 'Monthly Report',
      'reportsMonthlyTypeHourly': 'Hourly',
      'reportsMonthlyTypeFixed': 'Fixed Salary',
      'reportsMonthlyEmptyMessage': 'No records available for this month.',
      'reportsGrandTotalLabel': 'Grand Total',
      'reportsLoadingMessage': 'Fetching the latest summary...',
      'dashboardSummaryLoadFailedMessage':
          'Unable to load dashboard summary. Please try again.',
      'reportsLoadFailedMessage': 'Unable to load reports. Please try again.',
      'logoutConfirmationTitle': 'Confirm Logout',
      'logoutConfirmationMessage': 'Are you sure you want to logout?',
      'logoutConfirmButton': 'Logout',
      'logoutCancelButton': 'Cancel',
      'logoutSuccessMessage': 'User logged out successfully.',
      'logoutFailedMessage': 'Unable to log out. Please try again.',
      'deleteAccountConfirmationTitle': 'Delete Account',
      'deleteAccountConfirmationMessage':
          'Are you sure you want to delete your account? This action cannot be undone.',
      'deleteAccountConfirmButton': 'Delete',
      'deleteAccountCancelButton': 'Cancel',
      'deleteAccountSuccessMessage': 'Account deleted successfully.',
      'deleteAccountFailedMessage': 'Unable to delete account. Please try again.',
      'shareAppTitle': 'Share App',
      'shareViaWhatsApp': 'Share Via WhatsApp',
      'copyLink': 'Copy Link',
      'shareCancelButton': 'Cancel',
      'shareLinkCopied': 'Link copied to clipboard.',
      'shareWhatsappUnavailable': 'WhatsApp is not installed on this device.',
      'shareWhatsappFailed': 'Unable to open WhatsApp.',
      'shareMessage': 'Check out AttendancePro: {link}',
      'dashboardTappedMessage': 'Dashboard tapped',
      'addNewWorkTappedMessage': 'Add New Work tapped',
      'attendanceHistoryTappedMessage': 'Attendance History tapped',
      'contractWorkTappedMessage': 'Contract Work tapped',
      'helpSupportTappedMessage': 'Help & Support tapped',
      'workA': 'Work A',
      'workB': 'Work B',
      'switchedToWorkA': 'Switched to Work A',
      'switchedToWorkB': 'Switched to Work B',
      'selectLanguageTitle': 'Select Language',
      'languageEnglish': 'English',
      'languageHindi': 'Hindi',
      'languagePunjabi': 'Punjabi',
      'languageItalian': 'Italian',
      'languageSelection': 'Language: {language}',
      'noWorkAddedYet': 'No Work Added Yet',
      'startTrackingAttendance':
      'Start tracking your attendance \nby adding your first work',
      'addYourFirstWork': 'Add Your First Work',
      'hourlyWorkLabel': 'Hourly Work',
      'changeWorkButton': 'Change Work',
      'todaysAttendanceTitle': "Today's Attendance",
      'startTimeLabel': 'Start Time',
      'endTimeLabel': 'End Time',
      'breakLabel': 'Break Time',
      'attendanceSubmitButton': 'Submit',
      'attendanceStartTimeRequired': 'Start time is required',
      'attendanceEndTimeRequired': 'End time is required',
      'attendanceInvalidTimeFormat': 'Please enter time in HH:MM format',
      'attendanceBreakInvalid': 'Enter break time in minutes',
      'attendanceUnitsRequired': 'Units are required',
      'attendanceUnitsInvalid': 'Enter a valid number of units',
      'attendanceRateRequired': 'Rate per unit is required',
      'attendanceRateInvalid': 'Enter a valid rate per unit',
      'attendanceSubmitSuccess': 'Attendance saved successfully',
      'attendanceAlreadyMarkedMessage':
          'Attendance already marked for today. To make changes, please use the Edit option.',
      'attendanceSubmitFailed': 'Unable to save attendance. Please try again.',
      'attendanceMissedEntriesTitle': 'Complete pending attendance',
      'attendanceMissedEntriesDescription':
          'You missed attendance on the following dates. Please complete these entries before adding new ones.',
      'attendanceMissedEntriesListLabel': 'Pending dates',
      'attendanceMissedEntriesReviewButton': 'Review {date}',
      'attendanceMissedEntriesLoadFailed':
          'Unable to check pending attendance. Please try again.',
      'attendanceMissedEntriesResolveButton': 'Resolve now',
      'attendanceMissedEntriesCompleteSuccess':
          'Missed attendance completed successfully.',
      'attendanceMissedEntriesCompleteFailed':
          'Unable to complete missed attendance. Please try again.',
      'attendancePreviewTitle': 'Confirm attendance',
      'attendancePreviewDescription':
          'Review the details below before saving your attendance entry.',
      'attendancePreviewConfirmButton': 'Confirm & Save',
      'attendancePreviewCancelButton': 'Edit entry',
      'attendancePreviewHoursLabel': 'Calculated hours',
      'attendancePreviewSalaryLabel': 'Calculated salary',
      'attendancePreviewValidationPrompt': 'Are these hours correct?',
      'attendancePreviewFetchFailed':
          'Unable to preview attendance. Please try again.',
      'attendanceDateLabel': 'Date',
      'attendanceEntryTypeLabel': 'Entry type',
      'submitButton': 'Submit',
      'markAsWorkOffButton': 'Mark as Work Off',
      'contractWorkSummaryTitle': 'Contract Work Summary',
      'summaryLabel': 'Summary',
      'totalHoursLabel': 'Total Hours',
      'totalSalaryLabel': 'Total Salary',
      'activeWorkLabel': 'Active',
      'setActiveWorkButton': 'Set Active',
      'settingActiveWorkLabel': 'Activating...',
      'workActivatedMessage': 'Work set as active successfully.',
      'workActivatedWithNameMessage':
          'Your work {workName} is now active.',
      'workNameLabel': 'Work Name',
      'workNameHint': 'Ex Restaurant, Warehouse',
      'workNameTooShortValidation': 'Work name must be at least 3 characters.',
      'hourlySalaryLabel': 'Hourly Salary',
      'hourlySalaryHint': '€ 0.00',
      'hourlyRateNegativeValidation': 'Hourly rate cannot be negative.',
      'contractWorkHeader': 'Contract Work (if have)',
      'contractHistoryButton': 'View contract history',
      'addContractWorkButton': 'Add Contract Work',
      'contractWorkDescription':
          'Manage piece-rate items like Ravanello, Radish, Carrot or add your own.',
      'contractWorkCustomTypesTitle': 'Your contract types',
      'contractWorkNoCustomTypesLabel':
          'No contract type added yet. Please add a new contract in Work Details.',
      'contractWorkLoadError': 'Unable to load contract types right now.',
      'cancelButton': 'Cancel',
      'saveButtonLabel': 'Save',
      'saveWorkButton': 'Save Work',
      'saveChangesButton': 'Save changes',
      'deleteWorkButton': 'Delete Work',
      'workNameRequiredMessage': 'Please enter a work name.',
      'workAddedMessage': 'Work added successfully.',
      'workUpdatedMessage': 'Work updated successfully.',
      'invalidHourlyRateMessage': 'Please enter a valid hourly rate.',
      'editWorkTitle': 'Edit Work',
      'editWorkSubtitle': 'Update your work details',
      'editWorkDetailsTitle': 'Edit work details',
      'editWorkDetailsSubtitle':
          'Update the work name, hourly rate, or contract settings.',
      'updateWorkButton': 'Update Work',
      'editWorkTooltip': 'Edit work',
      'workDeleteConfirmationTitle': 'Delete Work',
      'workDeleteConfirmationMessage':
          'Are you sure you want to delete this work?',
      'workDeleteConfirmButton': 'Delete',
      'workDeleteCancelButton': 'Cancel',
      'workDeleteIrreversibleMessage':
          'Deleting this work will permanently remove related attendance history.',
      'workDeleteSuccessMessage': 'Work deleted successfully.',
      'workDeleteFailedMessage': 'Failed to delete work. Please try again.',
      'workSaveFailedMessage': 'Failed to save work. Please try again.',
      'worksLoadFailedTitle': 'Unable to load works',
      'worksLoadFailedMessage':
          'We couldn\'t fetch your works. Pull to refresh or try again.',
      'retryButtonLabel': 'Retry',
      'notAvailableLabel': 'Not available',
      'authenticationRequiredMessage': 'Your session has expired. Please log in again.',
      'walkthroughTitleOne': 'Track Your Work\n Hours Easily',
      'walkthroughDescOne':
      'Start and end your day with just one tap. Keep your hours accurate and organized.',
      'walkthroughTitleTwo': 'Add Multiple Jobs,\n One App',
      'walkthroughDescTwo':
      'Switch easily between multiple works and see your earnings instantly. One place for all your shifts.',
      'walkthroughTitleThree': 'Your Language.\n Your Way.',
      'walkthroughDescThree':
      'Available in English, Hindi, Punjabi, and Italian so you can manage attendance in your own comfort.',
      'skip': 'Skip',
      'splashTitle': 'AttendancePro',
      'loginTitle': 'Login',
      'loginPhoneTab': 'Phone',
      'loginEmailTab': 'Email',
      'loginIdentifierLabel': 'Email or Phone',
      'loginIdentifierHint': 'you@example.com or 9876543210',
      'loginPhoneLabel': 'Phone Number',
      'loginPhoneHint': 'Phone Number',
      'loginEmailLabel': 'Email Address',
      'loginEmailHint': 'Email',
      'emailLabel': 'Email',
      'emailHint': 'Email',
      'passwordLabel': 'Password',
      'passwordHint': '********',
      'loginButton': 'Login',
      'forgotPassword': 'Forgot Your Password?',
      'forgotPasswordSubtitle':
          'Enter your registered email to receive a verification code.',
      'forgotPasswordFieldLabel': 'Email Address',
      'forgotPasswordFieldHint': 'Email',
      'sendOtpButton': 'Send OTP',
      'backToLogin': 'Back to Login',
      'signupPromptPrefix': 'Don’t Have an Account? ',
      'signupPromptAction': 'Sign Up',
      'changeLanguage': 'Change Language',
      'snackEnterLoginIdentifier': 'Please enter your email or phone number.',
      'snackEnterValidLoginIdentifier': 'Please enter a valid email address or phone number.',
      'snackEnterPhone': 'Please enter your phone number.',
      'snackEnterValidPhone': 'Please enter a valid phone number.',
      'snackEnterEmail': 'Please enter your email.',
      'snackEnterValidEmail': 'Please enter a valid email address.',
      'snackEnterPassword': 'Please enter your password.',
      'snackLoginSuccess': 'Logged in successfully',
      'snackResetEmail': 'Please enter your email to reset.',
      'snackForgotInvalidEmail': 'Please enter a valid email address.',
      'signupTitle': 'Sign Up',
      'fullNameLabel': 'Full Name',
      'usernameLabel': 'Username',
      'usernameHint': 'Choose a unique username',
      'usernameRequired': 'Username required',
      'usernameInvalid':
          'Use 3-20 letters, numbers, dots, underscores, or hyphens',
      'nameRequired': 'Name required',
      'emailAddressLabel': 'Email Address',
      'emailRequired': 'Email required',
      'emailInvalid': 'Invalid email',
      'countryCodeLabel': 'Country Code',
      'phoneNumberLabel': 'Phone Number',
      'phoneNumberHint': '',
      'phoneRequired': 'Phone number required',
      'phoneInvalid': 'Enter a valid phone number',
      'languageLabel': 'Preferred Language',
      'passwordRequired': 'Password required',
      'passwordMinLength': 'Min 6 characters',
      'confirmPasswordLabel': 'Confirm Password',
      'confirmPasswordRequired': 'Please confirm password',
      'confirmPasswordMismatch': 'Passwords do not match',
      'termsAgreement': 'Please agree to the terms to continue.',
      'userAgreementTitle': 'Terms and Conditions & Privacy Policy',
      'userAgreementContent':
          'This is placeholder content for the Terms and Conditions and Privacy Policy. In a real app you would show the full text or open a webview.',
      'close': 'Close',
      'agreeTextPrefix': 'I Have Read and Agree to ',
      'userAgreement': 'Terms and Conditions',
      'and': ' and ',
      'privacyPolicy': 'Privacy Policy',
      'searchCountryCodes': 'Search country codes',
      'noCountryCodeResults': 'No countries found matching your search.',
      'policyLoadFailed': 'Unable to load the content. Please try again.',
      'policyRetryButton': 'Try again',
      'policyLastUpdatedLabel': 'Last updated',
      'signupButton': 'Sign Up',
      'alreadyAccountPrompt': 'Already Have an Account? ',
      'loginAction': 'Login',
      'createPasswordTitle': 'Create a New Password',
      'newPasswordLabel': 'New Password',
      'newPasswordHint': 'Enter new password',
      'confirmPasswordHint': 'Confirm password',
      'passwordMinEight': 'Password must be at least 6 characters.',
      'passwordsDoNotMatch': 'Passwords do not match.',
      'resetPasswordButton': 'Reset Password',
      'verifyNumberTitle': 'Verify Your Email',
      'verifyCodeDescription': 'We’ve sent a 6-digit code to your email.',
      'enterCodeLabel': 'Enter Code',
      'verifyOtpButton': 'Verify OTP',
      'resendPromptQuestion': 'Didn’t receive code?',
      'resendCountdown': 'Resend in 00:{seconds}',
      'resendCode': 'Resend Code',
      'operationSuccessful': 'Operation successful',
    },
    'hi': {
      'appTitle': 'अटेंडेंस प्रो',
      'drawerUserName': 'जॉन स्नो',
      'drawerUserPhone': '+39-319-055-5550',
      'dashboardLabel': 'कार्य सूची',
      'homeBannerTitle': 'उपस्थिति को स्मार्ट तरीके से ट्रैक करें',
      'homeBannerSubtitle':
          'अपनी शिफ्ट्स प्रबंधित करें, घंटे ट्रैक करें और हर दिन व्यवस्थित रहें।',
      'adPlaceholderTitle': 'यहाँ जल्द विज्ञापन आएगा',
      'adPlaceholderSubtitle':
          'हम जल्द ही यहाँ उपयोगी ऑफ़र दिखाएंगे। जुड़े रहें!',
      'addNewWorkLabel': 'नया कार्य जोड़ें',
      'selectWorkTitle': 'कार्य चुनें',
      'workSelectionSubtitle': 'रिपोर्ट देखने के लिए कार्य चुनें।',
      'confirmSelectionButton': 'चयन की पुष्टि करें',
      'workSelectionHourSuffix': '/घंटा',
      'attendanceHistoryLabel': 'उपस्थिति इतिहास',
      'attendanceHistoryMonthLabel': 'माह चुनें',
      'attendanceHistorySummaryTitle': 'इस महीने अब तक',
      'attendanceHistoryWorkedDaysLabel': 'काम किए गए दिन',
      'attendanceHistoryLeaveDaysLabel': 'छुट्टियाँ',
      'attendanceHistoryOvertimeLabel': 'अतिरिक्त समय',
      'attendanceHistoryTimelineTitle': 'दैनिक टाइमलाइन',
      'attendanceHistoryNoEntriesLabel': 'अभी कोई उपस्थिति रिकॉर्ड नहीं है।',
      'attendanceHistoryLoadFailedMessage':
          'उपस्थिति इतिहास लोड नहीं हो सका। कृपया पुनः प्रयास करें।',
      'attendanceHistoryHourlyEntry': 'घंटेवार',
      'attendanceHistoryContractEntry': 'कॉन्ट्रैक्ट',
      'attendanceHistoryLeaveEntry': 'छुट्टी',
      'attendanceHistoryPendingTitle': 'लंबित उपस्थिति प्रविष्टियाँ',
      'attendanceHistoryPendingDescription':
          'आज उपस्थित चिह्नित करने से पहले पिछले दिनों की प्रविष्टियाँ पूरी करें।',
      'attendanceHistoryResolveButton': 'अभी पूरा करें',
      'attendanceHistoryAllCaughtUp': 'आप पूरी तरह अपडेट हैं!',
      'attendanceHistoryAllCaughtUpDescription':
          'पिछली सभी उपस्थिति प्रविष्टियाँ पूरी हो चुकी हैं।',
      'attendanceHistoryAllWorks': 'सभी कार्य',
      'attendanceHistoryOvertimeEntryLabel': 'अतिरिक्त समय',
      'attendanceHistoryLoggedHoursLabel': 'लॉग किए गए घंटे',
      'attendanceHistoryReasonLabel': 'कारण',
      'contractReportDownloadLabel': 'Download contract report (PDF)',
      'historyReportDownloadLabel': 'Download attendance history (PDF)',
      'reportDownloadNoEntriesMessage':
          'No records are available for the selected view.',
      'reportDownloadSuccessMessage': 'PDF saved to {path}',
      'reportDownloadFailedMessage':
          'Unable to generate PDF report. Please try again.',
      'contractWorkLabel': 'ठेका कार्य',
      'contractWorkActiveRatesTitle': 'सक्रिय कॉन्ट्रैक्ट दरें',
      'contractWorkDefaultTypesTitle': 'कॉन्ट्रैक्ट प्रकार',
      'contractWorkRecentEntriesTitle': 'हाल की कॉन्ट्रैक्ट प्रविष्टियाँ',
      'contractWorkRatesNote': 'दरें केवल भविष्य की प्रविष्टियों पर लागू होंगी।',
      'contractWorkAddTypeTitle': 'कॉन्ट्रैक्ट प्रकार जोड़ें',
      'contractWorkEditTypeTitle': 'कॉन्ट्रैक्ट प्रकार अपडेट करें',
      'contractWorkSetupSubtitle':
          'कॉन्ट्रैक्ट कार्य प्रकार चुनें और दरें निर्धारित करें',
      'contractWorkContractTypeLabel': 'कॉन्ट्रैक्ट प्रकार',
      'contractWorkContractTypeHint': 'कॉन्ट्रैक्ट प्रकार चुनें',
      'contractWorkPricePerCrateLabel': 'प्रति क्रेट कीमत',
      'contractWorkSaveAllButton': 'सभी कॉन्ट्रैक्ट कार्य सहेजें',
      'contractWorkNameLabel': 'कॉन्ट्रैक्ट का नाम',
      'contractWorkSelectWorkHint': 'कार्य चुनें',
      'contractWorkCustomOption': 'कस्टम कार्य',
      'contractWorkRateLabel': 'दर',
      'contractWorkRateHint': 'दर दर्ज करें',
      'contractWorkPricePerBinHint': 'प्रति 1 बिन मूल्य',
      'contractWorkPricePerCrateHint': 'प्रति 1 क्रेट मूल्य',
      'contractWorkPricePerBunchesHint': 'प्रति 100 गुच्छे मूल्य',
      'contractWorkUnitLabel': 'इकाई लेबल',
      'contractWorkSubtypeLabel': 'प्रकार',
      'contractWorkSubtypeHint': 'प्रकार चुनें',
      'contractWorkSubtypeCustomOption': 'कस्टम उप प्रकार',
      'contractWorkSubtypeCustomLabel': 'कस्टम उप प्रकार',
      'contractWorkSubtypeRequiredMessage': 'कृपया प्रकार चुनें।',
      'contractWorkTypeLabel': 'प्रकार',
      'contractWorkTypeHint': 'प्रकार चुनें',
      'contractWorkTypeFixedOption': 'फिक्स्ड',
      'contractWorkTypeBundleOption': 'बंडल',
      'contractWorkRoleLabel': 'भूमिका',
      'contractWorkRoleHint': 'भूमिका चुनें',
      'contractWorkRoleRequiredMessage': 'कृपया भूमिका चुनें।',
      'contractWorkUnitsLabel': 'इकाइयाँ',
      'contractWorkUnitsHint': 'इकाइयों की संख्या दर्ज करें',
      'contractWorkRateRequiredMessage': 'कृपया मान्य दर दर्ज करें।',
      'contractWorkNameRequiredMessage': 'कृपया कोई कार्य नाम चुनें या दर्ज करें।',
      'contractWorkTypeSavedMessage': 'कॉन्ट्रैक्ट प्रकार सहेजा गया।',
      'contractWorkDeleteConfirmationTitle': 'कॉन्ट्रैक्ट प्रकार हटाएं',
      'contractWorkDeleteConfirmationMessage':
          'क्या आप वाकई इस कॉन्ट्रैक्ट प्रकार को हटाना चाहते हैं?',
      'contractWorkDeleteButton': 'हटाएं',
      'contractWorkTypeDeletedMessage': 'कॉन्ट्रैक्ट प्रकार हटाया गया।',
      'contractWorkTypeDeleteFailedMessage':
          'कॉन्ट्रैक्ट प्रकार हटाया नहीं जा सका। कृपया पुनः प्रयास करें।',
      'contractWorkNoEntriesLabel': 'कोई कॉन्ट्रैक्ट प्रविष्टि दर्ज नहीं है।',
      'contractWorkAllTypesAddedMessage':
          'सभी कॉन्ट्रैक्ट कार्य प्रकार पहले से जोड़े जा चुके हैं।',
      'contractWorkLastUpdatedLabel': 'आखिरी अपडेट',
      'contractWorkEditRateButton': 'दर अपडेट करें',
      'contractWorkActiveTypesLabel': 'सक्रिय प्रकार',
      'contractWorkTotalUnitsLabel': 'कुल इकाइयाँ',
      'contractWorkTotalSalaryLabel': 'कुल वेतन',
      'contractWorkDefaultTag': 'डिफ़ॉल्ट',
      'contractWorkUnitFallback': 'प्रति इकाई',
      'contractWorkCloseSheetLabel': 'कॉन्ट्रैक्ट विवरण शीट बंद करें',
      'profileLabel': 'प्रोफ़ाइल',
      'profileTitle': 'प्रोफ़ाइल संपादित करें',
      'profileNameLabel': 'पूरा नाम',
      'profileNameHint': 'अपना नाम दर्ज करें',
      'profileUsernameLabel': 'उपयोगकर्ता नाम',
      'profileUsernameHint': 'अपना उपयोगकर्ता नाम दर्ज करें',
      'profilePhoneLabel': 'फ़ोन नंबर',
      'profilePhoneHint': 'अपना फ़ोन नंबर दर्ज करें',
      'profileCountryCodeLabel': 'देश कोड',
      'profileCountryCodeHint': 'देश कोड दर्ज करें (जैसे +91)',
      'profileLanguageLabel': 'पसंदीदा भाषा',
      'profileSaveButton': 'परिवर्तन सहेजें',
      'profileUpdateSuccess': 'प्रोफ़ाइल सफलतापूर्वक अपडेट हुई।',
      'profileUpdateFailed': 'प्रोफ़ाइल अपडेट नहीं हो सकी। कृपया पुनः प्रयास करें।',
      'profileAuthRequired': 'कृपया अपनी प्रोफ़ाइल अपडेट करने के लिए दोबारा लॉगिन करें।',
      'profileValidationName': 'कृपया अपना नाम दर्ज करें।',
      'profileValidationUsername': 'कृपया अपना उपयोगकर्ता नाम दर्ज करें।',
      'profileValidationPhone': 'कृपया अपना फ़ोन नंबर दर्ज करें।',
      'profileValidationCountryCode': 'कृपया अपना देश कोड दर्ज करें।',
      'profileValidationLanguage': 'कृपया एक भाषा चुनें।',
      'profileLoadingFailed': 'प्रोफ़ाइल विवरण लोड नहीं हो सके।',
      'contractWorkCustomTypesTitle': 'आपके कॉन्ट्रैक्ट प्रकार',
      'contractWorkNoCustomTypesLabel':
          'अभी कोई कॉन्ट्रैक्ट प्रकार नहीं जोड़ा गया है। कृपया वर्क विवरण में नया कॉन्ट्रैक्ट जोड़ें।',
      'contractWorkLoadError': 'अभी कॉन्ट्रैक्ट प्रकार लोड नहीं हो पाए।',
      'changeLanguageLabel': 'भाषा बदलें',
      'helpSupportLabel': 'मदद और समर्थन',
      'helpSupportTitle': 'हम आपकी कैसे मदद कर सकते हैं?',
      'helpSupportSubtitle': 'त्वरित उत्तर पाएं या हमारी सपोर्ट टीम से संपर्क करें।',
      'helpSupportQuickActionsTitle': 'त्वरित सहायता',
      'helpSupportFaqsLabel': 'सामान्य प्रश्न',
      'helpSupportFaqsSubtitle': 'अक्सर पूछे गए प्रश्न देखें',
      'helpSupportGuidesLabel': 'शुरू कैसे करें',
      'helpSupportGuidesSubtitle': 'क्रमबद्ध मार्गदर्शिकाएँ',
      'helpSupportReportIssueLabel': 'समस्या रिपोर्ट करें',
      'helpSupportReportIssueSubtitle': 'हमें बताएं क्या गलत हुआ',
      'helpSupportContactTitle': 'संपर्क विकल्प',
      'helpSupportEmailLabel': 'हमें ईमेल करें',
      'helpSupportEmailValue': 'support@attendancepro.app',
      'helpSupportEmailButton': 'ईमेल भेजें',
      'helpSupportPhoneLabel': 'हमें कॉल करें',
      'helpSupportPhoneValue': '+91 9876543210',
      'helpSupportCallButton': 'अभी कॉल करें',
      'helpSupportChatLabel': 'लाइव चैट',
      'helpSupportChatSubtitle': 'सोम-शुक्र, सुबह 9 से शाम 6 तक उपलब्ध',
      'helpSupportChatButton': 'चैट प्रारंभ करें',
      'helpSupportHoursLabel': 'सपोर्ट समय',
      'helpSupportHoursValue': 'सोम - शुक्र, सुबह 9 से शाम 6 (GMT)',
      'helpSupportResponseTimeLabel': 'औसत प्रतिक्रिया समय',
      'helpSupportResponseTimeValue': '24 घंटे से कम',
      'helpSupportAdditionalInfoTitle': 'अतिरिक्त जानकारी',
      'helpSupportLastUpdatedLabel': 'अंतिम अपडेट',
      'helpSupportLastUpdatedValue': 'अक्टूबर 2025',
      'helpSupportPolicyLabel': 'सपोर्ट नीति',
      'helpSupportPolicyValue': 'हम AttendancePro ग्राहक सेवा मानकों का पालन करते हैं।',
      'helpSupportLaunchFailed': 'अनुरोधित ऐप्लिकेशन नहीं खोल सके।',
      'helpSupportComingSoon': 'यह अनुभाग जल्द ही उपलब्ध होगा।',
      'deleteAccountLabel': 'खाता हटाएँ',
      'logoutLabel': 'लॉग आउट',
      'reportsSummaryLabel': 'रिपोर्ट्स और सारांश',
      'reportsSummaryMonth': 'October 2025',
      'reportsCombinedSalaryTitle': 'Total Combined Salary',
      'reportsHoursWorkedSuffix': 'hours worked',
      'reportsUnitsCompletedSuffix': 'units completed',
      'reportsHourlyWorkSummaryTitle': 'Hourly Work Summary',
      'reportsWorkingDaysLabel': 'Working Days',
      'reportsAverageHoursPerDayLabel': 'Average Hours/Day',
      'reportsLastPayoutLabel': 'Last Payout',
      'reportsTotalUnitsLabel': 'Total Units',
      'reportsContractSalaryLabel': 'Contract Salary',
      'reportsBreakdownSuffix': 'Breakdown',
      'reportsMonthlySectionTitle': 'मासिक रिपोर्ट',
      'reportsMonthlyTypeHourly': 'घंटेवार',
      'reportsMonthlyTypeFixed': 'निश्चित वेतन',
      'reportsMonthlyEmptyMessage': 'इस महीने के लिए कोई रिकॉर्ड उपलब्ध नहीं हैं।',
      'reportsGrandTotalLabel': 'Grand Total',
      'reportsLoadingMessage': 'नवीनतम सारांश प्राप्त किया जा रहा है...',
      'dashboardSummaryLoadFailedMessage':
          'डैशबोर्ड सारांश लोड नहीं हो सका। कृपया पुनः प्रयास करें।',
      'reportsLoadFailedMessage': 'रिपोर्ट लोड नहीं हो सकीं। कृपया पुनः प्रयास करें।',
      'logoutConfirmationTitle': 'लॉग आउट की पुष्टि करें',
      'logoutConfirmationMessage': 'क्या आप वाकई लॉग आउट करना चाहते हैं?',
      'logoutConfirmButton': 'लॉग आउट',
      'logoutCancelButton': 'रद्द करें',
      'logoutSuccessMessage': 'उपयोगकर्ता सफलतापूर्वक लॉग आउट हुआ।',
      'logoutFailedMessage': 'लॉग आउट नहीं हो सका। कृपया पुनः प्रयास करें।',
      'deleteAccountConfirmationTitle': 'खाता हटाएँ',
      'deleteAccountConfirmationMessage':
          'क्या आप वाकई अपना खाता हटाना चाहते हैं? यह क्रिया वापस नहीं की जा सकती।',
      'deleteAccountConfirmButton': 'हटाएँ',
      'deleteAccountCancelButton': 'रद्द करें',
      'deleteAccountSuccessMessage': 'खाता सफलतापूर्वक हटाया गया।',
      'deleteAccountFailedMessage': 'खाता हटाने में असमर्थ। कृपया पुनः प्रयास करें।',
      'shareAppTitle': 'ऐप साझा करें',
      'shareViaWhatsApp': 'व्हाट्सऐप से साझा करें',
      'copyLink': 'लिंक कॉपी करें',
      'shareCancelButton': 'रद्द करें',
      'shareLinkCopied': 'लिंक कॉपी हो गया है।',
      'shareWhatsappUnavailable': 'इस डिवाइस पर WhatsApp इंस्टॉल नहीं है।',
      'shareWhatsappFailed': 'WhatsApp नहीं खोल सके।',
      'shareMessage': 'AttendancePro देखें: {link}',
      'dashboardTappedMessage': 'डैशबोर्ड चुना गया',
      'addNewWorkTappedMessage': 'नया कार्य चुना गया',
      'attendanceHistoryTappedMessage': 'उपस्थिति इतिहास चुना गया',
      'contractWorkTappedMessage': 'ठेका कार्य चुना गया',
      'helpSupportTappedMessage': 'मदद और समर्थन चुना गया',
      'workA': 'कार्य A',
      'workB': 'कार्य B',
      'switchedToWorkA': 'कार्य A पर स्विच किया गया',
      'switchedToWorkB': 'कार्य B पर स्विच किया गया',
      'selectLanguageTitle': 'भाषा चुनें',
      'languageEnglish': 'अंग्रेज़ी',
      'languageHindi': 'हिंदी',
      'languagePunjabi': 'पंजाबी',
      'languageItalian': 'इतालवी',
      'languageSelection': 'भाषा: {language}',
      'noWorkAddedYet': 'अभी तक कोई कार्य नहीं जोड़ा गया',
      'startTrackingAttendance':
      'अपनी पहली नौकरी जोड़कर\nअपनी उपस्थिति ट्रैक करना शुरू करें',
      'addYourFirstWork': 'अपना पहला कार्य जोड़ें',
      'hourlyWorkLabel': 'घंटे का कार्य',
      'changeWorkButton': 'कार्य बदलें',
      'todaysAttendanceTitle': 'आज की उपस्थिति',
      'startTimeLabel': 'आरंभ समय',
      'endTimeLabel': 'समाप्ति समय',
      'breakLabel': 'विराम समय',
      'attendanceSubmitButton': 'उपस्थिति सहेजें',
      'attendanceStartTimeRequired': 'आरंभ समय आवश्यक है',
      'attendanceEndTimeRequired': 'समाप्ति समय आवश्यक है',
      'attendanceInvalidTimeFormat': 'कृपया समय HH:MM प्रारूप में दर्ज करें',
      'attendanceBreakInvalid': 'ब्रेक समय मिनटों में दर्ज करें',
      'attendanceUnitsRequired': 'इकाइयाँ दर्ज करना आवश्यक है',
      'attendanceUnitsInvalid': 'कृपया मान्य इकाइयों की संख्या दर्ज करें',
      'attendanceRateRequired': 'प्रति इकाई दर आवश्यक है',
      'attendanceRateInvalid': 'कृपया मान्य प्रति इकाई दर दर्ज करें',
      'attendanceSubmitSuccess': 'उपस्थिति सफलतापूर्वक सहेजी गई',
      'attendanceAlreadyMarkedMessage':
          'आज की उपस्थिति पहले ही दर्ज की जा चुकी है। बदलाव करने के लिए कृपया संपादन विकल्प का उपयोग करें।',
      'attendanceSubmitFailed': 'उपस्थिति सहेजने में असमर्थ। कृपया पुनः प्रयास करें।',
      'attendanceMissedEntriesTitle': 'लंबित उपस्थिति पूरी करें',
      'attendanceMissedEntriesDescription':
          'आपने निम्न तिथियों पर उपस्थिति दर्ज नहीं की है। नई प्रविष्टि जोड़ने से पहले इन्हें पूरा करें।',
      'attendanceMissedEntriesListLabel': 'लंबित तिथियाँ',
      'attendanceMissedEntriesReviewButton': 'समीक्षा करें {date}',
      'attendanceMissedEntriesLoadFailed':
          'लंबित उपस्थिति की जांच नहीं हो सकी। कृपया पुनः प्रयास करें।',
      'attendanceMissedEntriesResolveButton': 'अभी हल करें',
      'attendanceMissedEntriesCompleteSuccess':
          'छूटी हुई उपस्थिति सफलतापूर्वक पूरी हो गई।',
      'attendanceMissedEntriesCompleteFailed':
          'छूटी हुई उपस्थिति पूरी नहीं हो सकी। कृपया फिर प्रयास करें।',
      'attendancePreviewTitle': 'उपस्थिति की पुष्टि करें',
      'attendancePreviewDescription':
          'उपस्थिति सहेजने से पहले नीचे दिए विवरण की जाँच करें।',
      'attendancePreviewConfirmButton': 'पुष्टि करें और सहेजें',
      'attendancePreviewCancelButton': 'प्रविष्टि संपादित करें',
      'attendancePreviewHoursLabel': 'गणना किए गए घंटे',
      'attendancePreviewSalaryLabel': 'गणना किया गया वेतन',
      'attendancePreviewValidationPrompt': 'क्या ये घंटे सही हैं?',
      'attendancePreviewFetchFailed':
          'उपस्थिति प्रीव्यू लोड नहीं हो पाया। कृपया पुनः प्रयास करें।',
      'attendanceDateLabel': 'तारीख',
      'attendanceEntryTypeLabel': 'प्रविष्टि प्रकार',
      'submitButton': 'जमा करें',
      'markAsWorkOffButton': 'कार्य अवकाश चिह्नित करें',
      'contractWorkSummaryTitle': 'ठेका कार्य सारांश',
      'summaryLabel': 'सारांश',
      'totalHoursLabel': 'कुल घंटे',
      'totalSalaryLabel': 'कुल वेतन',
      'activeWorkLabel': 'सक्रिय',
      'setActiveWorkButton': 'सक्रिय करें',
      'settingActiveWorkLabel': 'सक्रिय किया जा रहा है...',
      'workActivatedMessage': 'कार्य सफलतापूर्वक सक्रिय किया गया।',
      'workActivatedWithNameMessage':
          'आपका कार्य {workName} अब सक्रिय है।',
      'workNameLabel': 'कार्य का नाम',
      'workNameHint': 'उदाहरण: रेस्टोरेंट, गोदाम',
      'workNameTooShortValidation': 'कार्य का नाम कम से कम 3 अक्षरों का होना चाहिए।',
      'hourlySalaryLabel': 'घंटे की मजदूरी',
      'hourlySalaryHint': '€ 0.00',
      'hourlyRateNegativeValidation': 'घंटे की दर नकारात्मक नहीं हो सकती।',
      'contractWorkHeader': 'ठेका कार्य (यदि हो)',
      'contractHistoryButton': 'कॉन्ट्रैक्ट इतिहास देखें',
      'addContractWorkButton': 'ठेका कार्य जोड़ें',
      'contractWorkDescription':
          'पीस-रेट कार्य जैसे रावनेलो, मूली, गाजर जोड़ें या अपना नया बनाएं।',
      'cancelButton': 'रद्द करें',
      'saveButtonLabel': 'सहेजें',
      'saveWorkButton': 'कार्य सहेजें',
      'saveChangesButton': 'परिवर्तन सहेजें',
      'deleteWorkButton': 'काम हटाएं',
      'workNameRequiredMessage': 'कृपया कार्य का नाम दर्ज करें।',
      'workAddedMessage': 'कार्य सफलतापूर्वक जोड़ा गया।',
      'workUpdatedMessage': 'कार्य सफलतापूर्वक अपडेट किया गया।',
      'invalidHourlyRateMessage': 'कृपया मान्य प्रति घंटा दर दर्ज करें।',
      'editWorkTitle': 'कार्य संपादित करें',
      'editWorkSubtitle': 'अपने कार्य का विवरण अपडेट करें',
      'editWorkDetailsTitle': 'कार्य विवरण संपादित करें',
      'editWorkDetailsSubtitle':
          'कार्य का नाम, प्रति घंटा दर या कॉन्ट्रैक्ट सेटिंग्स अपडेट करें',
      'updateWorkButton': 'कार्य अपडेट करें',
      'editWorkTooltip': 'कार्य संपादित करें',
      'workDeleteConfirmationTitle': 'काम हटाएं',
      'workDeleteConfirmationMessage':
          'क्या आप वाकई इस काम को हटाना चाहते हैं?',
      'workDeleteConfirmButton': 'हटाएं',
      'workDeleteCancelButton': 'रद्द करें',
      'workDeleteIrreversibleMessage':
          'इस कार्य को हटाने से संबंधित सभी उपस्थिति इतिहास स्थायी रूप से हट जाएगा।',
      'workDeleteSuccessMessage': 'काम सफलतापूर्वक हटाया गया।',
      'workDeleteFailedMessage': 'काम हटाने में विफल। कृपया पुनः प्रयास करें।',
      'workSaveFailedMessage': 'कार्य सहेजा नहीं जा सका। कृपया पुनः प्रयास करें।',
      'worksLoadFailedTitle': 'कार्य लोड नहीं हो सका',
      'worksLoadFailedMessage':
          'हम आपके कार्य लोड नहीं कर पाए। कृपया नीचे खींचकर रिफ्रेश करें या पुनः प्रयास करें।',
      'retryButtonLabel': 'पुनः प्रयास करें',
      'notAvailableLabel': 'उपलब्ध नहीं',
      'authenticationRequiredMessage': 'आपका सत्र समाप्त हो गया है। कृपया पुनः लॉग इन करें।',
      'walkthroughTitleOne': 'अपने कार्य घंटों को आसानी से ट्रैक करें',
      'walkthroughDescOne':
      'सिर्फ एक टैप में अपना दिन शुरू और खत्म करें। अपने घंटे सटीक और व्यवस्थित रखें।',
      'walkthroughTitleTwo': 'कई नौकरियाँ, एक ऐप',
      'walkthroughDescTwo':
      'आसानी से कई कामों के बीच स्विच करें और अपनी कमाई तुरंत देखें।',
      'walkthroughTitleThree': 'आपकी भाषा, आपका तरीका',
      'walkthroughDescThree':
      'अंग्रेज़ी, हिंदी, पंजाबी और इतालवी में उपलब्ध ताकि आप अपनी सुविधा से उपस्थिति प्रबंधित कर सकें।',
      'skip': 'स्किप करें',
      'splashTitle': 'अटेंडेंस प्रो',
      'loginTitle': 'लॉगिन',
      'loginPhoneTab': 'फोन',
      'loginEmailTab': 'ईमेल',
      'loginIdentifierLabel': 'ईमेल या फोन नंबर',
      'loginIdentifierHint': 'you@example.com या 9876543210',
      'loginPhoneLabel': 'फोन नंबर',
      'loginPhoneHint': '+91 98765 43210',
      'loginEmailLabel': 'ईमेल पता',
      'loginEmailHint': 'ईमेल',
      'emailLabel': 'ईमेल',
      'emailHint': 'ईमेल',
      'passwordLabel': 'पासवर्ड',
      'passwordHint': '********',
      'loginButton': 'लॉगिन',
      'forgotPassword': 'क्या आपने पासवर्ड भूल गए?',
      'forgotPasswordSubtitle':
          'सत्यापन कोड प्राप्त करने के लिए अपना पंजीकृत ईमेल दर्ज करें।',
      'forgotPasswordFieldLabel': 'ईमेल पता',
      'forgotPasswordFieldHint': 'ईमेल',
      'sendOtpButton': 'ओटीपी भेजें',
      'backToLogin': 'लॉगिन पर वापस जाएं',
      'signupPromptPrefix': 'खाता नहीं है? ',
      'signupPromptAction': 'साइन अप',
      'changeLanguage': 'भाषा बदलें',
      'snackEnterLoginIdentifier': 'कृपया अपना ईमेल या फोन नंबर दर्ज करें।',
      'snackEnterValidLoginIdentifier': 'कृपया मान्य ईमेल पता या फोन नंबर दर्ज करें।',
      'snackEnterPhone': 'कृपया अपना फोन नंबर दर्ज करें।',
      'snackEnterValidPhone': 'कृपया मान्य फोन नंबर दर्ज करें।',
      'snackEnterEmail': 'कृपया अपना ईमेल दर्ज करें।',
      'snackEnterValidEmail': 'कृपया मान्य ईमेल पता दर्ज करें।',
      'snackEnterPassword': 'कृपया अपना पासवर्ड दर्ज करें।',
      'snackLoginSuccess': 'सफलतापूर्वक लॉगिन किया गया',
      'snackResetEmail': 'रीसेट करने के लिए कृपया अपना ईमेल दर्ज करें।',
      'snackForgotInvalidEmail': 'कृपया मान्य ईमेल पता दर्ज करें।',
      'signupTitle': 'साइन अप',
      'fullNameLabel': 'पूरा नाम',
      'usernameLabel': 'उपयोगकर्ता नाम',
      'usernameHint': 'एक अद्वितीय उपयोगकर्ता नाम चुनें',
      'usernameRequired': 'उपयोगकर्ता नाम आवश्यक है',
      'usernameInvalid':
          '3-20 अक्षर, अंक, डॉट, अंडरस्कोर या हाइफ़न का उपयोग करें',
      'nameRequired': 'नाम आवश्यक है',
      'emailAddressLabel': 'ईमेल पता',
      'emailRequired': 'ईमेल आवश्यक है',
      'emailInvalid': 'अमान्य ईमेल',
      'countryCodeLabel': 'देश का कोड',
      'phoneNumberLabel': 'फ़ोन नंबर',
      'phoneNumberHint': '',
      'phoneRequired': 'फ़ोन नंबर आवश्यक है',
      'phoneInvalid': 'कृपया मान्य फ़ोन नंबर दर्ज करें',
      'languageLabel': 'पसंदीदा भाषा',
      'passwordRequired': 'पासवर्ड आवश्यक है',
      'passwordMinLength': 'कम से कम 6 अक्षर',
      'confirmPasswordLabel': 'पासवर्ड की पुष्टि करें',
      'confirmPasswordRequired': 'कृपया पासवर्ड की पुष्टि करें',
      'confirmPasswordMismatch': 'पासवर्ड मेल नहीं खाते',
      'termsAgreement': 'जारी रखने के लिए कृपया शर्तों से सहमत हों।',
      'userAgreementTitle': 'नियम और शर्तें एवं गोपनीयता नीति',
      'userAgreementContent':
      'यह नियम और शर्तें और गोपनीयता नीति के लिए प्लेसहोल्डर है। वास्तविक ऐप में आप पूरा पाठ दिखाएंगे या वेबव्यू खोलेंगे।',
      'close': 'बंद करें',
      'agreeTextPrefix': 'मैंने पढ़ा है और सहमत हूँ ',
      'userAgreement': 'नियम और शर्तें',
      'and': ' और ',
      'privacyPolicy': 'गोपनीयता नीति',
      'searchCountryCodes': 'देश कोड खोजें',
      'noCountryCodeResults': 'कोई देश आपके खोज से मेल नहीं खाता।',
      'policyLoadFailed': 'सामग्री लोड नहीं हो पाई। कृपया पुनः प्रयास करें।',
      'policyRetryButton': 'पुनः प्रयास करें',
      'policyLastUpdatedLabel': 'अंतिम अद्यतन',
      'signupButton': 'साइन अप',
      'alreadyAccountPrompt': 'पहले से खाता है? ',
      'loginAction': 'लॉगिन',
      'createPasswordTitle': 'नया पासवर्ड बनाएं',
      'newPasswordLabel': 'नया पासवर्ड',
      'newPasswordHint': 'नया पासवर्ड दर्ज करें',
      'confirmPasswordHint': 'पासवर्ड की पुष्टि करें',
      'passwordMinEight': 'पासवर्ड कम से कम 6 अक्षरों का होना चाहिए।',
      'passwordsDoNotMatch': 'पासवर्ड मेल नहीं खाते।',
      'resetPasswordButton': 'पासवर्ड रीसेट करें',
      'verifyNumberTitle': 'अपना ईमेल सत्यापित करें',
      'verifyCodeDescription': 'हमने आपके ईमेल पर 6 अंकों का कोड भेजा है।',
      'enterCodeLabel': 'कोड दर्ज करें',
      'verifyOtpButton': 'ओटीपी सत्यापित करें',
      'resendPromptQuestion': 'कोड नहीं मिला?',
      'resendCountdown': '00:{seconds} में फिर से भेजें',
      'resendCode': 'कोड पुनः भेजें',
      'operationSuccessful': 'कार्रवाई सफल रही',
    },
    'pa': {
      'appTitle': 'ਅਟੈਂਡੈਂਸ ਪ੍ਰੋ',
      'drawerUserName': 'ਜੌਨ ਸਨੋ',
      'drawerUserPhone': '+39-319-055-5550',
      'dashboardLabel': 'ਕੰਮਾਂ ਦੀ ਸੂਚੀ',
      'homeBannerTitle': 'ਹਾਜ਼ਰੀ ਨੂੰ ਹੋਰ ਸਮਝਦਾਰੀ ਨਾਲ ਟਰੈਕ ਕਰੋ',
      'homeBannerSubtitle':
          'ਆਪਣੀਆਂ ਸ਼ਿਫਟਾਂ ਸੰਭਾਲੋ, ਘੰਟੇ ਟਰੈਕ ਕਰੋ ਅਤੇ ਹਰ ਰੋਜ਼ ਸੁਵਿਧਾਜਨਕ ਰਹੋ।',
      'adPlaceholderTitle': 'ਇੱਥੇ ਜਲਦੀ ਵਿਗਿਆਪਨ ਆਏਗਾ',
      'adPlaceholderSubtitle':
          'ਅਸੀਂ ਜਲਦੀ ਹੀ ਇੱਥੇ ਲਾਹੇਵੰਦ ਔਫ਼ਰ ਦਿਖਾਵਾਂਗੇ। ਬਣੇ ਰਹੋ!',
      'addNewWorkLabel': 'ਨਵਾਂ ਕੰਮ ਜੋੜੋ',
      'selectWorkTitle': 'ਕੰਮ ਚੁਣੋ',
      'workSelectionSubtitle': 'ਰਿਪੋਰਟ ਦੇਖਣ ਲਈ ਕੰਮ ਚੁਣੋ।',
      'confirmSelectionButton': 'ਚੋਣ ਦੀ ਪੁਸ਼ਟੀ ਕਰੋ',
      'workSelectionHourSuffix': '/ਘੰਟਾ',
      'attendanceHistoryLabel': 'ਹਾਜ਼ਰੀ ਇਤਿਹਾਸ',
      'attendanceHistoryMonthLabel': 'ਮਹੀਨਾ ਚੁਣੋ',
      'attendanceHistorySummaryTitle': 'ਇਸ ਮਹੀਨੇ ਤੱਕ',
      'attendanceHistoryWorkedDaysLabel': 'ਕੰਮ ਵਾਲੇ ਦਿਨ',
      'attendanceHistoryLeaveDaysLabel': 'ਛੁੱਟੀਆਂ',
      'attendanceHistoryOvertimeLabel': 'ਵਾਧੂ ਸਮਾਂ',
      'attendanceHistoryTimelineTitle': 'ਰੋਜ਼ਾਨਾ ਟਾਈਮਲਾਈਨ',
      'attendanceHistoryNoEntriesLabel': 'ਹਾਲੇ ਕੋਈ ਹਾਜ਼ਰੀ ਰਿਕਾਰਡ ਨਹੀਂ ਹੈ।',
      'attendanceHistoryLoadFailedMessage':
          'ਹਾਜ਼ਰੀ ਇਤਿਹਾਸ ਲੋਡ ਨਹੀਂ ਹੋ ਸਕਿਆ। ਕਿਰਪਾ ਕਰਕੇ ਦੁਬਾਰਾ ਕੋਸ਼ਿਸ਼ ਕਰੋ।',
      'attendanceHistoryHourlyEntry': 'ਘੰਟਾ ਅਧਾਰਿਤ',
      'attendanceHistoryContractEntry': 'ਕਾਂਟ੍ਰੈਕਟ',
      'attendanceHistoryLeaveEntry': 'ਛੁੱਟੀ',
      'attendanceHistoryPendingTitle': 'ਬਕਾਇਆ ਹਾਜ਼ਰੀ ਐਂਟਰੀਆਂ',
      'attendanceHistoryPendingDescription':
          'ਅੱਜ ਹਾਜ਼ਰ ਕਰਨ ਤੋਂ ਪਹਿਲਾਂ ਪਿਛਲੇ ਦਿਨਾਂ ਦੀਆਂ ਐਂਟਰੀਆਂ ਪੂਰੀ ਕਰੋ।',
      'attendanceHistoryResolveButton': 'ਹੁਣ ਪੂਰਾ ਕਰੋ',
      'attendanceHistoryAllCaughtUp': 'ਤੁਸੀਂ ਪੂਰੀ ਤਰ੍ਹਾਂ ਅਪਡੇਟ ਹੋ!',
      'attendanceHistoryAllCaughtUpDescription':
          'ਪਿਛਲੀਆਂ ਸਾਰੀਆਂ ਹਾਜ਼ਰੀ ਐਂਟਰੀਆਂ ਪੂਰੀਆਂ ਹਨ।',
      'attendanceHistoryAllWorks': 'ਸਾਰੇ ਕੰਮ',
      'attendanceHistoryOvertimeEntryLabel': 'ਵਾਧੂ ਸਮਾਂ',
      'attendanceHistoryLoggedHoursLabel': 'ਲਾਗ ਕੀਤੇ ਘੰਟੇ',
      'attendanceHistoryReasonLabel': 'ਕਾਰਨ',
      'contractReportDownloadLabel': 'Download contract report (PDF)',
      'historyReportDownloadLabel': 'Download attendance history (PDF)',
      'reportDownloadNoEntriesMessage':
          'No records are available for the selected view.',
      'reportDownloadSuccessMessage': 'PDF saved to {path}',
      'reportDownloadFailedMessage':
          'Unable to generate PDF report. Please try again.',
      'contractWorkLabel': 'ਕਾਂਟ੍ਰੈਕਟ ਕੰਮ',
      'contractWorkActiveRatesTitle': 'ਸਰਗਰਮ ਕਾਂਟ੍ਰੈਕਟ ਦਰਾਂ',
      'contractWorkDefaultTypesTitle': 'ਕਾਂਟ੍ਰੈਕਟ ਕਿਸਮਾਂ',
      'contractWorkRecentEntriesTitle': 'ਤਾਜ਼ੀਆਂ ਕਾਂਟ੍ਰੈਕਟ ਐਂਟਰੀਆਂ',
      'contractWorkRatesNote': 'ਦਰਾਂ ਸਿਰਫ਼ ਭਵਿੱਖ ਦੀਆਂ ਐਂਟਰੀਆਂ \'ਤੇ ਲਾਗੂ ਹੁੰਦੀਆਂ ਹਨ।',
      'contractWorkAddTypeTitle': 'ਕਾਂਟ੍ਰੈਕਟ ਕਿਸਮ ਸ਼ਾਮਲ ਕਰੋ',
      'contractWorkEditTypeTitle': 'ਕਾਂਟ੍ਰੈਕਟ ਕਿਸਮ ਅਪਡੇਟ ਕਰੋ',
      'contractWorkSetupSubtitle':
          'ਕਰਾਰ ਕੰਮ ਦੀਆਂ ਕਿਸਮਾਂ ਚੁਣੋ ਅਤੇ ਦਰਾਂ ਨਿਰਧਾਰਤ ਕਰੋ',
      'contractWorkContractTypeLabel': 'ਕਰਾਰ ਕਿਸਮ',
      'contractWorkContractTypeHint': 'ਕਰਾਰ ਕਿਸਮ ਚੁਣੋ',
      'contractWorkPricePerCrateLabel': 'ਪ੍ਰਤੀ ਕਰੇਟ ਕੀਮਤ',
      'contractWorkSaveAllButton': 'ਸਾਰੇ ਕਰਾਰ ਕੰਮ ਸੰਭਾਲੋ',
      'contractWorkNameLabel': 'ਕਾਂਟ੍ਰੈਕਟ ਨਾਮ',
      'contractWorkSelectWorkHint': 'ਕੰਮ ਚੁਣੋ',
      'contractWorkCustomOption': 'ਕਸਟਮ ਕੰਮ',
      'contractWorkRateLabel': 'ਦਰ',
      'contractWorkRateHint': 'ਦਰ ਦਰਜ ਕਰੋ',
      'contractWorkPricePerBinHint': '1 ਬਿਨ ਪ੍ਰਤੀ ਕੀਮਤ',
      'contractWorkPricePerCrateHint': '1 ਕਰੇਟ ਪ੍ਰਤੀ ਕੀਮਤ',
      'contractWorkPricePerBunchesHint': '100 ਗੁੱਛਿਆਂ ਪ੍ਰਤੀ ਕੀਮਤ',
      'contractWorkUnitLabel': 'ਯੂਨਿਟ ਲੇਬਲ',
      'contractWorkSubtypeLabel': 'ਕਿਸਮ',
      'contractWorkSubtypeHint': 'ਕਿਸਮ ਚੁਣੋ',
      'contractWorkSubtypeCustomOption': 'ਕਸਟਮ ਉਪ-ਕਿਸਮ',
      'contractWorkSubtypeCustomLabel': 'ਕਸਟਮ ਉਪ-ਕਿਸਮ',
      'contractWorkSubtypeRequiredMessage': 'ਕਿਰਪਾ ਕਰਕੇ ਕਿਸਮ ਚੁਣੋ।',
      'contractWorkTypeLabel': 'ਕਿਸਮ',
      'contractWorkTypeHint': 'ਕਿਸਮ ਚੁਣੋ',
      'contractWorkTypeFixedOption': 'ਫਿਕਸਡ',
      'contractWorkTypeBundleOption': 'ਬੰਡਲ',
      'contractWorkRoleLabel': 'ਭੂਮਿਕਾ',
      'contractWorkRoleHint': 'ਭੂਮਿਕਾ ਚੁਣੋ',
      'contractWorkRoleRequiredMessage': 'ਕਿਰਪਾ ਕਰਕੇ ਭੂਮਿਕਾ ਚੁਣੋ।',
      'contractWorkUnitsLabel': 'ਯੂਨਿਟ',
      'contractWorkUnitsHint': 'ਯੂਨਿਟ ਦਰਜ ਕਰੋ',
      'contractWorkRateRequiredMessage': 'ਕਿਰਪਾ ਕਰਕੇ ਵੈਧ ਦਰ ਦਰਜ ਕਰੋ।',
      'contractWorkNameRequiredMessage':
          'ਕਿਰਪਾ ਕਰਕੇ ਕੋਈ ਕੰਮ ਦਾ ਨਾਮ ਚੁਣੋ ਜਾਂ ਦਰਜ ਕਰੋ।',
      'contractWorkTypeSavedMessage': 'ਕਾਂਟ੍ਰੈਕਟ ਕਿਸਮ ਸੇਵ ਕੀਤੀ ਗਈ।',
      'contractWorkDeleteConfirmationTitle': 'ਕਾਂਟ੍ਰੈਕਟ ਕਿਸਮ ਮਿਟਾਓ',
      'contractWorkDeleteConfirmationMessage':
          'ਕੀ ਤੁਸੀਂ ਇਹ ਕਾਂਟ੍ਰੈਕਟ ਕਿਸਮ ਮਿਟਾਉਣਾ ਚਾਹੁੰਦੇ ਹੋ?',
      'contractWorkDeleteButton': 'ਮਿਟਾਓ',
      'contractWorkTypeDeletedMessage': 'ਕਾਂਟ੍ਰੈਕਟ ਕਿਸਮ ਮਿਟਾਈ ਗਈ ਹੈ।',
      'contractWorkTypeDeleteFailedMessage':
          'ਕਾਂਟ੍ਰੈਕਟ ਕਿਸਮ ਮਿਟਾਈ ਨਹੀਂ ਜਾ ਸਕੀ। ਦੁਬਾਰਾ ਕੋਸ਼ਿਸ਼ ਕਰੋ।',
      'contractWorkNoEntriesLabel': 'ਕੋਈ ਕਾਂਟ੍ਰੈਕਟ ਐਂਟਰੀ ਰਿਕਾਰਡ ਨਹੀਂ ਹੈ।',
      'contractWorkAllTypesAddedMessage':
          'ਸਾਰੇ ਕਰਾਰ ਕੰਮ ਕਿਸਮਾਂ ਪਹਿਲਾਂ ਹੀ ਜੋੜੀਆਂ ਜਾ ਚੁੱਕੀਆਂ ਹਨ।',
      'contractWorkLastUpdatedLabel': 'ਆਖਰੀ ਅਪਡੇਟ',
      'contractWorkEditRateButton': 'ਦਰ ਅਪਡੇਟ ਕਰੋ',
      'contractWorkActiveTypesLabel': 'ਸਰਗਰਮ ਕਿਸਮਾਂ',
      'contractWorkTotalUnitsLabel': 'ਕੁੱਲ ਯੂਨਿਟ',
      'contractWorkTotalSalaryLabel': 'ਕੁੱਲ ਤਨਖ਼ਾਹ',
      'contractWorkDefaultTag': 'ਡਿਫਾਲਟ',
      'contractWorkUnitFallback': 'ਪਰ ਯੂਨਿਟ',
      'contractWorkCloseSheetLabel': 'ਕਰਾਰ ਵੇਰਵਾ ਸ਼ੀਟ ਬੰਦ ਕਰੋ',
      'profileLabel': 'ਪ੍ਰੋਫ਼ਾਈਲ',
      'profileTitle': 'ਪ੍ਰੋਫ਼ਾਈਲ ਸੋਧੋ',
      'profileNameLabel': 'ਪੂਰਾ ਨਾਮ',
      'profileNameHint': 'ਆਪਣਾ ਨਾਮ ਦਰਜ ਕਰੋ',
      'profileUsernameLabel': 'ਯੂਜ਼ਰਨੇਮ',
      'profileUsernameHint': 'ਆਪਣਾ ਯੂਜ਼ਰਨੇਮ ਦਰਜ ਕਰੋ',
      'profilePhoneLabel': 'ਫੋਨ ਨੰਬਰ',
      'profilePhoneHint': 'ਆਪਣਾ ਫੋਨ ਨੰਬਰ ਦਰਜ ਕਰੋ',
      'profileCountryCodeLabel': 'ਦੇਸ਼ ਕੋਡ',
      'profileCountryCodeHint': 'ਦੇਸ਼ ਕੋਡ ਦਰਜ ਕਰੋ (ਜਿਵੇਂ +91)',
      'profileLanguageLabel': 'ਪਸੰਦੀਦਾ ਭਾਸ਼ਾ',
      'profileSaveButton': 'ਬਦਲਾਅ ਸੇਵ ਕਰੋ',
      'profileUpdateSuccess': 'ਪ੍ਰੋਫ਼ਾਈਲ ਸਫਲਤਾਪੂਰਵਕ ਅੱਪਡੇਟ ਹੋ ਗਈ ਹੈ।',
      'profileUpdateFailed': 'ਪ੍ਰੋਫ਼ਾਈਲ ਅੱਪਡੇਟ ਨਹੀਂ ਹੋ ਸਕੀ। ਕਿਰਪਾ ਕਰਕੇ ਦੁਬਾਰਾ ਕੋਸ਼ਿਸ਼ ਕਰੋ।',
      'profileAuthRequired': 'ਕਿਰਪਾ ਕਰਕੇ ਆਪਣੀ ਪ੍ਰੋਫ਼ਾਈਲ ਅੱਪਡੇਟ ਕਰਨ ਲਈ ਦੁਬਾਰਾ ਲਾਗਿਨ ਕਰੋ।',
      'profileValidationName': 'ਕਿਰਪਾ ਕਰਕੇ ਆਪਣਾ ਨਾਮ ਦਰਜ ਕਰੋ।',
      'profileValidationUsername': 'ਕਿਰਪਾ ਕਰਕੇ ਆਪਣਾ ਯੂਜ਼ਰਨੇਮ ਦਰਜ ਕਰੋ।',
      'profileValidationPhone': 'ਕਿਰਪਾ ਕਰਕੇ ਆਪਣਾ ਫੋਨ ਨੰਬਰ ਦਰਜ ਕਰੋ।',
      'profileValidationCountryCode': 'ਕਿਰਪਾ ਕਰਕੇ ਆਪਣਾ ਦੇਸ਼ ਕੋਡ ਦਰਜ ਕਰੋ।',
      'profileValidationLanguage': 'ਕਿਰਪਾ ਕਰਕੇ ਕੋਈ ਭਾਸ਼ਾ ਚੁਣੋ।',
      'profileLoadingFailed': 'ਪ੍ਰੋਫ਼ਾਈਲ ਵੇਰਵੇ ਲੋਡ ਨਹੀਂ ਹੋ ਸਕੇ।',
      'contractWorkCustomTypesTitle': 'ਤੁਹਾਡੀਆਂ ਕਾਂਟ੍ਰੈਕਟ ਕਿਸਮਾਂ',
      'contractWorkNoCustomTypesLabel':
          'ਹਾਲੇ ਤੱਕ ਕੋਈ ਕਾਂਟ੍ਰੈਕਟ ਕਿਸਮ ਨਹੀਂ ਜੋੜੀ ਗਈ। ਕਿਰਪਾ ਕਰਕੇ ਵਰਕ ਵੇਰਵਿਆਂ ਵਿੱਚ ਨਵਾਂ ਕਾਂਟ੍ਰੈਕਟ ਸ਼ਾਮਲ ਕਰੋ।',
      'contractWorkLoadError': 'ਇਸ ਵੇਲੇ ਕਾਂਟ੍ਰੈਕਟ ਕਿਸਮਾਂ ਲੋਡ ਨਹੀਂ ਹੋ ਸਕੀਆਂ।',
      'changeLanguageLabel': 'ਭਾਸ਼ਾ ਬਦਲੋ',
      'helpSupportLabel': 'ਸਹਾਇਤਾ ਅਤੇ ਸਮਰਥਨ',
      'helpSupportTitle': 'ਅਸੀਂ ਤੁਹਾਡੀ ਕਿਵੇਂ ਮਦਦ ਕਰ ਸਕਦੇ ਹਾਂ?',
      'helpSupportSubtitle': 'ਝਟਪਟ ਜਵਾਬ ਲੱਭੋ ਜਾਂ ਸਾਡੀ ਸਹਾਇਤਾ ਟੀਮ ਨਾਲ ਸੰਪਰਕ ਕਰੋ।',
      'helpSupportQuickActionsTitle': 'ਤੁਰੰਤ ਮਦਦ',
      'helpSupportFaqsLabel': 'ਅਕਸਰ ਪੁੱਛੇ ਸਵਾਲ',
      'helpSupportFaqsSubtitle': 'ਆਮ ਸਵਾਲ ਵੇਖੋ',
      'helpSupportGuidesLabel': 'ਸ਼ੁਰੂਆਤ ਲਈ ਗਾਈਡ',
      'helpSupportGuidesSubtitle': 'ਕਦਮ-ਦਰ-ਕਦਮ ਸਿਖਲਾਈ',
      'helpSupportReportIssueLabel': 'ਮੁੱਦਾ ਰਿਪੋਰਟ ਕਰੋ',
      'helpSupportReportIssueSubtitle': 'ਸਾਨੂੰ ਦੱਸੋ ਕਿ ਕੀ ਗਲਤ ਹੋਇਆ',
      'helpSupportContactTitle': 'ਸੰਪਰਕ ਵਿਕਲਪ',
      'helpSupportEmailLabel': 'ਸਾਨੂੰ ਈਮੇਲ ਕਰੋ',
      'helpSupportEmailValue': 'support@attendancepro.com',
      'helpSupportEmailButton': 'ਈਮੇਲ ਭੇਜੋ',
      'helpSupportPhoneLabel': 'ਸਾਨੂੰ ਕਾਲ ਕਰੋ',
      'helpSupportPhoneValue': '+91 9876543210',
      'helpSupportCallButton': 'ਹੁਣੇ ਕਾਲ ਕਰੋ',
      'helpSupportChatLabel': 'ਲਾਈਵ ਚੈਟ',
      'helpSupportChatSubtitle': 'ਸੋਮ-ਸ਼ੁੱਕਰ, ਸਵੇਰੇ 9 ਤੋਂ ਸ਼ਾਮ 6 ਵਜੇ ਤੱਕ',
      'helpSupportChatButton': 'ਚੈਟ ਸ਼ੁਰੂ ਕਰੋ',
      'helpSupportHoursLabel': 'ਸਹਾਇਤਾ ਸਮਾਂ',
      'helpSupportHoursValue': 'ਸੋਮ - ਸ਼ੁੱਕਰ, 9 AM - 6 PM (GMT)',
      'helpSupportResponseTimeLabel': 'ਔਸਤ ਜਵਾਬ ਸਮਾਂ',
      'helpSupportResponseTimeValue': '24 ਘੰਟਿਆਂ ਤੋਂ ਘੱਟ',
      'helpSupportAdditionalInfoTitle': 'ਵਾਧੂ ਜਾਣਕਾਰੀ',
      'helpSupportLastUpdatedLabel': 'ਆਖਰੀ ਅੱਪਡੇਟ',
      'helpSupportLastUpdatedValue': 'ਅਕਤੂਬਰ 2025',
      'helpSupportPolicyLabel': 'ਸਹਾਇਤਾ ਨੀਤੀ',
      'helpSupportPolicyValue': 'ਅਸੀਂ AttendancePro ਗਾਹਕ ਸੇਵਾ ਮਿਆਰਾਂ ਦੀ ਪਾਲਣਾ ਕਰਦੇ ਹਾਂ।',
      'helpSupportLaunchFailed': 'ਅਨੁਰੋਧਿਤ ਐਪ ਖੋਲ੍ਹਣ ਵਿੱਚ ਅਸਮਰੱਥ।',
      'helpSupportComingSoon': 'ਇਹ ਭਾਗ ਜਲਦੀ ਉਪਲਬਧ ਹੋਵੇਗਾ।',
      'deleteAccountLabel': 'ਖਾਤਾ ਮਿਟਾਓ',
      'logoutLabel': 'ਲੌਗ ਆਉਟ',
      'reportsSummaryLabel': 'ਰਿਪੋਰਟਾਂ ਅਤੇ ਸਾਰਾਂਸ਼',
      'reportsSummaryMonth': 'October 2025',
      'reportsCombinedSalaryTitle': 'Total Combined Salary',
      'reportsHoursWorkedSuffix': 'hours worked',
      'reportsUnitsCompletedSuffix': 'units completed',
      'reportsHourlyWorkSummaryTitle': 'Hourly Work Summary',
      'reportsWorkingDaysLabel': 'Working Days',
      'reportsAverageHoursPerDayLabel': 'Average Hours/Day',
      'reportsLastPayoutLabel': 'Last Payout',
      'reportsTotalUnitsLabel': 'Total Units',
      'reportsContractSalaryLabel': 'Contract Salary',
      'reportsBreakdownSuffix': 'Breakdown',
      'reportsMonthlySectionTitle': 'ਮਾਸਿਕ ਰਿਪੋਰਟ',
      'reportsMonthlyTypeHourly': 'ਘੰਟਾ ਅਧਾਰਿਤ',
      'reportsMonthlyTypeFixed': 'ਨਿਰਧਾਰਤ ਤਨਖਾਹ',
      'reportsMonthlyEmptyMessage': 'ਇਸ ਮਹੀਨੇ ਲਈ ਕੋਈ ਰਿਕਾਰਡ ਉਪਲਬਧ ਨਹੀਂ ਹਨ।',
      'reportsGrandTotalLabel': 'Grand Total',
      'reportsLoadingMessage': 'ਤਾਜ਼ਾ ਸੰਖੇਪ ਲਿਆ ਜਾ ਰਿਹਾ ਹੈ...',
      'dashboardSummaryLoadFailedMessage':
          'ਡੈਸ਼ਬੋਰਡ ਸੰਖੇਪ ਲੋਡ ਨਹੀਂ ਹੋ ਸਕਿਆ। ਕਿਰਪਾ ਕਰਕੇ ਦੁਬਾਰਾ ਕੋਸ਼ਿਸ਼ ਕਰੋ।',
      'reportsLoadFailedMessage': 'ਰਿਪੋਰਟ ਲੋਡ ਨਹੀਂ ਹੋ ਸਕੀਆਂ। ਕਿਰਪਾ ਕਰਕੇ ਮੁੜ ਕੋਸ਼ਿਸ਼ ਕਰੋ।',
      'logoutConfirmationTitle': 'ਲਾਗਆਉਟ ਦੀ ਪੁਸ਼ਟੀ ਕਰੋ',
      'logoutConfirmationMessage': 'ਕੀ ਤੁਸੀਂ ਯਕੀਨਨ ਲਾਗਆਉਟ ਕਰਨਾ ਚਾਹੁੰਦੇ ਹੋ?',
      'logoutConfirmButton': 'ਲਾਗਆਉਟ',
      'logoutCancelButton': 'ਰੱਦ ਕਰੋ',
      'logoutSuccessMessage': 'ਉਪਭੋਗਤਾ ਸਫਲਤਾਪੂਰਵਕ ਲਾਗਆਉਟ ਹੋ ਗਿਆ।',
      'logoutFailedMessage': 'ਲਾਗਆਉਟ ਨਹੀਂ ਹੋ ਸਕਿਆ। ਦੁਬਾਰਾ ਕੋਸ਼ਿਸ਼ ਕਰੋ।',
      'deleteAccountConfirmationTitle': 'ਖਾਤਾ ਮਿਟਾਓ',
      'deleteAccountConfirmationMessage':
          'ਕੀ ਤੁਸੀਂ ਵਾਕਈ ਆਪਣਾ ਖਾਤਾ ਮਿਟਾਉਣਾ ਚਾਹੁੰਦੇ ਹੋ? ਇਹ ਕਿਰਿਆ ਵਾਪਸ ਨਹੀਂ ਕੀਤੀ ਜਾ ਸਕਦੀ।',
      'deleteAccountConfirmButton': 'ਮਿਟਾਓ',
      'deleteAccountCancelButton': 'ਰੱਦ ਕਰੋ',
      'deleteAccountSuccessMessage': 'ਖਾਤਾ ਸਫਲਤਾਪੂਰਵਕ ਮਿਟਾਇਆ ਗਿਆ ਹੈ।',
      'deleteAccountFailedMessage': 'ਖਾਤਾ ਮਿਟਾਉਣ ਵਿੱਚ ਅਸਫਲ। ਕਿਰਪਾ ਕਰਕੇ ਦੁਬਾਰਾ ਕੋਸ਼ਿਸ਼ ਕਰੋ।',
      'shareAppTitle': 'ਐਪ ਸਾਂਝਾ ਕਰੋ',
      'shareViaWhatsApp': 'WhatsApp ਰਾਹੀਂ ਸਾਂਝਾ ਕਰੋ',
      'copyLink': 'ਲਿੰਕ ਕਾਪੀ ਕਰੋ',
      'shareCancelButton': 'ਰੱਦ ਕਰੋ',
      'shareLinkCopied': 'ਲਿੰਕ ਕਲਿੱਪਬੋਰਡ ਵਿੱਚ ਕਾਪੀ ਹੋ ਗਿਆ ਹੈ।',
      'shareWhatsappUnavailable': 'ਇਸ ਡਿਵਾਈਸ ਤੇ WhatsApp ਇੰਸਟਾਲ ਨਹੀਂ ਹੈ।',
      'shareWhatsappFailed': 'WhatsApp ਨਹੀਂ ਖੋਲ੍ਹ ਸਕੇ।',
      'shareMessage': 'AttendancePro ਨੂੰ ਵੇਖੋ: {link}',
      'dashboardTappedMessage': 'ਡੈਸ਼ਬੋਰਡ ਚੁਣਿਆ ਗਿਆ',
      'addNewWorkTappedMessage': 'ਨਵਾਂ ਕੰਮ ਚੁਣਿਆ ਗਿਆ',
      'attendanceHistoryTappedMessage': 'ਹਾਜ਼ਰੀ ਇਤਿਹਾਸ ਚੁਣਿਆ ਗਿਆ',
      'contractWorkTappedMessage': 'ਕਾਂਟ੍ਰੈਕਟ ਕੰਮ ਚੁਣਿਆ ਗਿਆ',
      'helpSupportTappedMessage': 'ਸਹਾਇਤਾ ਅਤੇ ਸਮਰਥਨ ਚੁਣਿਆ ਗਿਆ',
      'workA': 'ਕੰਮ A',
      'workB': 'ਕੰਮ B',
      'switchedToWorkA': 'ਕੰਮ A ਤੇ ਬਦਲਿਆ ਗਿਆ',
      'switchedToWorkB': 'ਕੰਮ B ਤੇ ਬਦਲਿਆ ਗਿਆ',
      'selectLanguageTitle': 'ਭਾਸ਼ਾ ਚੁਣੋ',
      'languageEnglish': 'ਅੰਗਰੇਜ਼ੀ',
      'languageHindi': 'ਹਿੰਦੀ',
      'languagePunjabi': 'ਪੰਜਾਬੀ',
      'languageItalian': 'ਇਤਾਲਵੀ',
      'languageSelection': 'ਭਾਸ਼ਾ: {language}',
      'noWorkAddedYet': 'ਹੁਣ ਤੱਕ ਕੋਈ ਕੰਮ ਨਹੀਂ ਜੋੜਿਆ ਗਿਆ',
      'startTrackingAttendance':
      'ਆਪਣਾ ਪਹਿਲਾ ਕੰਮ ਜੋੜ ਕੇ\nਹਾਜ਼ਰੀ ਟ੍ਰੈਕ ਕਰਨੀ ਸ਼ੁਰੂ ਕਰੋ',
      'addYourFirstWork': 'ਆਪਣਾ ਪਹਿਲਾ ਕੰਮ ਜੋੜੋ',
      'hourlyWorkLabel': 'ਘੰਟਾਵਾਰੀ ਕੰਮ',
      'changeWorkButton': 'ਕੰਮ ਬਦਲੋ',
      'todaysAttendanceTitle': 'ਅੱਜ ਦੀ ਹਾਜ਼ਰੀ',
      'startTimeLabel': 'ਸ਼ੁਰੂਆਤੀ ਸਮਾਂ',
      'endTimeLabel': 'ਖਤਮ ਸਮਾਂ',
      'breakLabel': 'ਵਿਰਾਮ ਦਾ ਸਮਾਂ',
      'attendanceSubmitButton': 'ਹਾਜ਼ਰੀ ਸੰਭਾਲੋ',
      'attendanceStartTimeRequired': 'ਸ਼ੁਰੂ ਕਰਨ ਦਾ ਸਮਾਂ ਲਾਜ਼ਮੀ ਹੈ',
      'attendanceEndTimeRequired': 'ਖਤਮ ਕਰਨ ਦਾ ਸਮਾਂ ਲਾਜ਼ਮੀ ਹੈ',
      'attendanceInvalidTimeFormat': 'ਕਿਰਪਾ ਕਰਕੇ ਸਮਾਂ HH:MM ਫਾਰਮੈਟ ਵਿੱਚ ਦਰਜ ਕਰੋ',
      'attendanceBreakInvalid': 'ਬ੍ਰੇਕ ਦਾ ਸਮਾਂ ਮਿੰਟਾਂ ਵਿੱਚ ਲਿਖੋ',
      'attendanceUnitsRequired': 'ਯੂਨਿਟ ਦਰਜ ਕਰਨਾ ਲਾਜ਼ਮੀ ਹੈ',
      'attendanceUnitsInvalid': 'ਕਿਰਪਾ ਕਰਕੇ ਯੂਨਿਟਾਂ ਦੀ ਵੈਧ ਗਿਣਤੀ ਦਰਜ ਕਰੋ',
      'attendanceRateRequired': 'ਪ੍ਰਤੀ ਯੂਨਿਟ ਦਰ ਲਾਜ਼ਮੀ ਹੈ',
      'attendanceRateInvalid': 'ਕਿਰਪਾ ਕਰਕੇ ਵੈਧ ਪ੍ਰਤੀ ਯੂਨਿਟ ਦਰ ਦਰਜ ਕਰੋ',
      'attendanceSubmitSuccess': 'ਹਾਜ਼ਰੀ ਸਫਲਤਾਪੂਰਵਕ ਸੰਭਾਲੀ ਗਈ',
      'attendanceAlreadyMarkedMessage':
          'ਅੱਜ ਦੀ ਹਾਜ਼ਰੀ ਪਹਿਲਾਂ ਹੀ ਦਰਜ ਕੀਤੀ ਜਾ ਚੁੱਕੀ ਹੈ। ਤਬਦੀਲੀਆਂ ਲਈ ਕਿਰਪਾ ਕਰਕੇ ਐਡਿਟ ਵਿਕਲਪ ਵਰਤੋਂ।',
      'attendanceSubmitFailed': 'ਹਾਜ਼ਰੀ ਸੰਭਾਲਣ ਵਿੱਚ ਅਸਮਰੱਥ। ਦੁਬਾਰਾ ਕੋਸ਼ਿਸ਼ ਕਰੋ।',
      'attendanceMissedEntriesTitle': 'ਬਕਾਇਆ ਹਾਜ਼ਰੀ ਪੂਰੀ ਕਰੋ',
      'attendanceMissedEntriesDescription':
          'ਤੁਸੀਂ ਹੇਠਾਂ ਦਿੱਤੀਆਂ ਤਾਰੀਆਂ ’ਤੇ ਹਾਜ਼ਰੀ ਨਹੀਂ ਭਰੀ। ਨਵੀਂ ਐਂਟਰੀ ਜੋੜਨ ਤੋਂ ਪਹਿਲਾਂ ਇਨ੍ਹਾਂ ਨੂੰ ਪੂਰਾ ਕਰੋ।',
      'attendanceMissedEntriesListLabel': 'ਬਕਾਇਆ ਤਾਰੀਆਂ',
      'attendanceMissedEntriesReviewButton': 'ਸਮੀਖਿਆ ਕਰੋ {date}',
      'attendanceMissedEntriesLoadFailed':
          'ਬਕਾਇਆ ਹਾਜ਼ਰੀ ਦੀ ਜਾਂਚ ਨਹੀਂ ਹੋ ਸਕੀ। ਕਿਰਪਾ ਕਰਕੇ ਦੁਬਾਰਾ ਕੋਸ਼ਿਸ਼ ਕਰੋ।',
      'attendanceMissedEntriesResolveButton': 'ਹੁਣੇ ਹੱਲ ਕਰੋ',
      'attendanceMissedEntriesCompleteSuccess':
          'ਰਿਹਿ ਗਈ ਹਾਜ਼ਰੀ ਸਫਲਤਾਪੂਰਵਕ ਪੂਰੀ ਹੋ ਗਈ ਹੈ।',
      'attendanceMissedEntriesCompleteFailed':
          'ਰਿਹਿ ਗਈ ਹਾਜ਼ਰੀ ਪੂਰੀ ਨਹੀਂ ਹੋ ਸਕੀ। ਕਿਰਪਾ ਕਰਕੇ ਦੁਬਾਰਾ ਕੋਸ਼ਿਸ਼ ਕਰੋ।',
      'attendancePreviewTitle': 'ਹਾਜ਼ਰੀ ਦੀ ਪੁਸ਼ਟੀ ਕਰੋ',
      'attendancePreviewDescription':
          'ਹਾਜ਼ਰੀ ਸੇਵ ਕਰਨ ਤੋਂ ਪਹਿਲਾਂ ਹੇਠਾਂ ਦਿੱਤੀ ਜਾਣਕਾਰੀ ਦੀ ਜਾਂਚ ਕਰੋ।',
      'attendancePreviewConfirmButton': 'ਪੁਸ਼ਟੀ ਕਰੋ ਅਤੇ ਸੇਵ ਕਰੋ',
      'attendancePreviewCancelButton': 'ਐਂਟਰੀ ਸੋਧੋ',
      'attendancePreviewHoursLabel': 'ਗਿਣੇ ਘੰਟੇ',
      'attendancePreviewSalaryLabel': 'ਗਿਣੀ ਤਨਖ਼ਾਹ',
      'attendancePreviewValidationPrompt': 'ਕੀ ਇਹ ਘੰਟੇ ਠੀਕ ਹਨ?',
      'attendancePreviewFetchFailed':
          'ਹਾਜ਼ਰੀ ਪ੍ਰੀਵਿਊ ਲੋਡ ਨਹੀਂ ਹੋ ਸਕਿਆ। ਕਿਰਪਾ ਕਰਕੇ ਦੁਬਾਰਾ ਕੋਸ਼ਿਸ਼ ਕਰੋ।',
      'attendanceDateLabel': 'ਮਿਤੀ',
      'attendanceEntryTypeLabel': 'ਐਂਟਰੀ ਕਿਸਮ',
      'submitButton': 'ਜਮ੍ਹਾਂ ਕਰੋ',
      'markAsWorkOffButton': 'ਕੰਮ ਛੁੱਟੀ ਨਿਸ਼ਾਨ ਲਗਾਓ',
      'contractWorkSummaryTitle': 'ਕਾਨਟ੍ਰੈਕਟ ਕੰਮ ਸੰਖੇਪ',
      'summaryLabel': 'ਸੰਖੇਪ',
      'totalHoursLabel': 'ਕੁੱਲ ਘੰਟੇ',
      'totalSalaryLabel': 'ਕੁੱਲ ਤਨਖ਼ਾਹ',
      'activeWorkLabel': 'ਸਰਗਰਮ',
      'setActiveWorkButton': 'ਸਰਗਰਮ ਕਰੋ',
      'settingActiveWorkLabel': 'ਸਰਗਰਮ ਕੀਤਾ ਜਾ ਰਿਹਾ ਹੈ...',
      'workActivatedMessage': 'ਕੰਮ ਨੂੰ ਸਰਗਰਮ ਕੀਤਾ ਗਿਆ ਹੈ।',
      'workActivatedWithNameMessage':
          'ਤੁਹਾਡਾ ਕੰਮ {workName} ਹੁਣ ਸਰਗਰਮ ਹੈ।',
      'workNameLabel': 'ਕੰਮ ਦਾ ਨਾਮ',
      'workNameHint': 'ਉਦਾਹਰਣ: ਰੈਸਟੋਰੈਂਟ, ਗੋਦਾਮ',
      'workNameTooShortValidation': 'ਕੰਮ ਦਾ ਨਾਮ ਘੱਟੋ-ਘੱਟ 3 ਅੱਖਰਾਂ ਦਾ ਹੋਣਾ ਚਾਹੀਦਾ ਹੈ।',
      'hourlySalaryLabel': 'ਘੰਟਾਵਾਰੀ ਮਜ਼ਦੂਰੀ',
      'hourlySalaryHint': '€ 0.00',
      'hourlyRateNegativeValidation': 'ਘੰਟੇ ਦੀ ਦਰ ਨਕਾਰਾਤਮਕ ਨਹੀਂ ਹੋ ਸਕਦੀ।',
      'contractWorkHeader': 'ਕਾਂਟ੍ਰੈਕਟ ਕੰਮ (ਜੇ ਹੋਵੇ)',
      'contractHistoryButton': 'ਕਾਂਟ੍ਰੈਕਟ ਇਤਿਹਾਸ ਵੇਖੋ',
      'addContractWorkButton': 'ਕਾਂਟ੍ਰੈਕਟ ਕੰਮ ਜੋੜੋ',
      'contractWorkDescription':
          'ਰਾਵੇਨੇਲੋ, ਮੂਲੀ, ਗਾਜਰ ਵਰਗੇ ਪੀਸ-ਰੇਟ ਕੰਮ ਜੋੜੋ ਜਾਂ ਆਪਣਾ ਬਣਾਓ।',
      'cancelButton': 'ਰੱਦ ਕਰੋ',
      'saveButtonLabel': 'ਸੇਵ ਕਰੋ',
      'saveWorkButton': 'ਕੰਮ ਸੰਭਾਲੋ',
      'saveChangesButton': 'ਤਬਦੀਲੀਆਂ ਸੰਭਾਲੋ',
      'deleteWorkButton': 'ਕੰਮ ਮਿਟਾਓ',
      'workNameRequiredMessage': 'ਕਿਰਪਾ ਕਰਕੇ ਕੰਮ ਦਾ ਨਾਮ ਦਰਜ ਕਰੋ।',
      'workAddedMessage': 'ਕੰਮ ਸਫਲਤਾਪੂਰਵਕ ਜੋੜਿਆ ਗਿਆ।',
      'workUpdatedMessage': 'ਕੰਮ ਸਫਲਤਾਪੂਰਵਕ ਅੱਪਡੇਟ ਹੋਇਆ।',
      'invalidHourlyRateMessage': 'ਕਿਰਪਾ ਕਰਕੇ ਠੀਕ ਘੰਟਾਵਾਰੀ ਦਰ ਦਰਜ ਕਰੋ।',
      'editWorkTitle': 'ਕੰਮ ਸੰਪਾਦਿਤ ਕਰੋ',
      'editWorkSubtitle': 'ਆਪਣੇ ਕੰਮ ਦੇ ਵੇਰਵੇ ਅੱਪਡੇਟ ਕਰੋ',
      'editWorkDetailsTitle': 'ਕੰਮ ਦੇ ਵੇਰਵੇ ਸੰਪਾਦਿਤ ਕਰੋ',
      'editWorkDetailsSubtitle':
          'ਕੰਮ ਦਾ ਨਾਮ, ਘੰਟਾਵਾਰੀ ਰੇਟ ਜਾਂ ਠੇਕੇ ਦੀਆਂ ਸੈਟਿੰਗਾਂ ਅੱਪਡੇਟ ਕਰੋ',
      'updateWorkButton': 'ਕੰਮ ਅੱਪਡੇਟ ਕਰੋ',
      'editWorkTooltip': 'ਕੰਮ ਸੰਪਾਦਿਤ ਕਰੋ',
      'workDeleteConfirmationTitle': 'ਕੰਮ ਮਿਟਾਓ',
      'workDeleteConfirmationMessage': 'ਕੀ ਤੁਸੀਂ ਇਹ ਕੰਮ ਮਿਟਾਉਣਾ ਚਾਹੁੰਦੇ ਹੋ?',
      'workDeleteConfirmButton': 'ਮਿਟਾਓ',
      'workDeleteCancelButton': 'ਰੱਦ ਕਰੋ',
      'workDeleteIrreversibleMessage':
          'ਇਹ ਕੰਮ ਮਿਟਾਉਣ ਨਾਲ ਸੰਬੰਧਿਤ ਹਾਜ਼ਰੀ ਇਤਿਹਾਸ ਸਥਾਈ ਤੌਰ \'ਤੇ ਹਟ ਜਾਵੇਗਾ।',
      'workDeleteSuccessMessage': 'ਕੰਮ ਸਫਲਤਾਪੂਰਵਕ ਮਿਟਾਇਆ ਗਿਆ।',
      'workDeleteFailedMessage': 'ਕੰਮ ਮਿਟਾਉਣ ਵਿੱਚ ਅਸਫਲ। ਕਿਰਪਾ ਕਰਕੇ ਦੁਬਾਰਾ ਕੋਸ਼ਿਸ਼ ਕਰੋ।',
      'workSaveFailedMessage': 'ਕੰਮ ਸੰਭਾਲਿਆ ਨਹੀਂ ਜਾ ਸਕਿਆ। ਕਿਰਪਾ ਕਰਕੇ ਮੁੜ ਕੋਸ਼ਿਸ਼ ਕਰੋ।',
      'worksLoadFailedTitle': 'ਕੰਮ ਲੋਡ ਨਹੀਂ ਹੋ ਸਕੇ',
      'worksLoadFailedMessage':
          'ਅਸੀਂ ਤੁਹਾਡੇ ਕੰਮ ਲੋਡ ਨਹੀਂ ਕਰ ਸਕੇ। ਕਿਰਪਾ ਕਰਕੇ ਹੇਠਾਂ ਖਿੱਚ ਕੇ ਰਿਫ਼ਰੈਸ਼ ਕਰੋ ਜਾਂ ਮੁੜ ਕੋਸ਼ਿਸ਼ ਕਰੋ।',
      'retryButtonLabel': 'ਮੁੜ ਕੋਸ਼ਿਸ਼ ਕਰੋ',
      'notAvailableLabel': 'ਉਪਲਬਧ ਨਹੀਂ',
      'authenticationRequiredMessage': 'ਤੁਹਾਡਾ ਸੈਸ਼ਨ ਸਮਾਪਤ ਹੋ ਗਿਆ ਹੈ। ਕਿਰਪਾ ਕਰਕੇ ਦੁਬਾਰਾ ਲੌਗਇਨ ਕਰੋ।',
      'walkthroughTitleOne':
      'ਆਪਣੇ ਕੰਮ ਦੇ ਘੰਟੇ ਆਸਾਨੀ ਨਾਲ ਟ੍ਰੈਕ ਕਰੋ',
      'walkthroughDescOne':
      'ਕੇਵਲ ਇੱਕ ਟੈਪ ਨਾਲ ਆਪਣਾ ਦਿਨ ਸ਼ੁਰੂ ਅਤੇ ਖਤਮ ਕਰੋ। ਆਪਣੇ ਘੰਟਿਆਂ ਨੂੰ ਸਹੀ ਅਤੇ ਵਿਵਸਥਿਤ ਰੱਖੋ।',
      'walkthroughTitleTwo': 'ਇੱਕ ਐਪ ਵਿੱਚ ਕਈ ਨੌਕਰੀਆਂ',
      'walkthroughDescTwo':
      'ਅਸਾਨੀ ਨਾਲ ਕਈ ਕੰਮਾਂ ਵਿੱਚ ਬਦਲੋ ਅਤੇ ਆਪਣੀ ਕਮਾਈ ਤੁਰੰਤ ਵੇਖੋ।',
      'walkthroughTitleThree': 'ਤੁਹਾਡੀ ਭਾਸ਼ਾ, ਤੁਹਾਡਾ ਢੰਗ',
      'walkthroughDescThree':
      'ਅੰਗਰੇਜ਼ੀ, ਹਿੰਦੀ, ਪੰਜਾਬੀ ਅਤੇ ਇਤਾਲਵੀ ਵਿੱਚ ਉਪਲਬਧ ਤਾਂ ਜੋ ਤੁਸੀਂ ਹਾਜ਼ਰੀ ਆਪਣੇ ਸੁਖ ਨਾਲ ਸੰਭਾਲ ਸਕੋ।',
      'skip': 'ਛੱਡੋ',
      'splashTitle': 'ਅਟੈਂਡੈਂਸ ਪ੍ਰੋ',
      'loginTitle': 'ਲਾਗਇਨ',
      'loginPhoneTab': 'ਫੋਨ',
      'loginEmailTab': 'ਈਮੇਲ',
      'loginIdentifierLabel': 'ਈਮੇਲ ਜਾਂ ਫੋਨ ਨੰਬਰ',
      'loginIdentifierHint': 'you@example.com ਜਾਂ 9876543210',
      'loginPhoneLabel': 'ਫੋਨ ਨੰਬਰ',
      'loginPhoneHint': '+91 98765 43210',
      'loginEmailLabel': 'ਈਮੇਲ ਪਤਾ',
      'loginEmailHint': 'ਈਮੇਲ',
      'emailLabel': 'ਈਮੇਲ',
      'emailHint': 'ਈਮੇਲ',
      'passwordLabel': 'ਪਾਸਵਰਡ',
      'passwordHint': '********',
      'loginButton': 'ਲਾਗਇਨ',
      'forgotPassword': 'ਕੀ ਤੁਸੀਂ ਪਾਸਵਰਡ ਭੁੱਲ ਗਏ?',
      'forgotPasswordSubtitle':
          'ਪੁਸ਼ਟੀਕਰਨ ਕੋਡ ਪ੍ਰਾਪਤ ਕਰਨ ਲਈ ਆਪਣਾ ਰਜਿਸਟਰਡ ਈਮੇਲ ਦਰਜ ਕਰੋ।',
      'forgotPasswordFieldLabel': 'ਈਮੇਲ ਪਤਾ',
      'forgotPasswordFieldHint': 'ਈਮੇਲ',
      'sendOtpButton': 'ਓਟੀਪੀ ਭੇਜੋ',
      'backToLogin': "ਲਾਗਇਨ 'ਤੇ ਵਾਪਸ ਜਾਓ",
      'signupPromptPrefix': 'ਖਾਤਾ ਨਹੀਂ ਹੈ? ',
      'signupPromptAction': 'ਸਾਈਨ ਅੱਪ',
      'changeLanguage': 'ਭਾਸ਼ਾ ਬਦਲੋ',
      'snackEnterLoginIdentifier': 'ਕਿਰਪਾ ਕਰਕੇ ਆਪਣਾ ਈਮੇਲ ਜਾਂ ਫੋਨ ਨੰਬਰ ਦਰਜ ਕਰੋ।',
      'snackEnterValidLoginIdentifier': 'ਕਿਰਪਾ ਕਰਕੇ ਵੈਧ ਈਮੇਲ ਐਡਰੈੱਸ ਜਾਂ ਫੋਨ ਨੰਬਰ ਦਰਜ ਕਰੋ।',
      'snackEnterPhone': 'ਕਿਰਪਾ ਕਰਕੇ ਆਪਣਾ ਫੋਨ ਨੰਬਰ ਦਰਜ ਕਰੋ।',
      'snackEnterValidPhone': 'ਕਿਰਪਾ ਕਰਕੇ ਵੈਧ ਫੋਨ ਨੰਬਰ ਦਰਜ ਕਰੋ।',
      'snackEnterEmail': 'ਕਿਰਪਾ ਕਰਕੇ ਆਪਣਾ ਈਮੇਲ ਦਰਜ ਕਰੋ।',
      'snackEnterValidEmail': 'ਕਿਰਪਾ ਕਰਕੇ ਵੈਧ ਈਮੇਲ ਐਡਰੈੱਸ ਦਰਜ ਕਰੋ।',
      'snackEnterPassword': 'ਕਿਰਪਾ ਕਰਕੇ ਆਪਣਾ ਪਾਸਵਰਡ ਦਰਜ ਕਰੋ।',
      'snackLoginSuccess': 'ਸਫਲਤਾਪੂਰਵਕ ਲਾਗਇਨ ਕੀਤਾ',
      'snackResetEmail': 'ਰੀਸੈਟ ਕਰਨ ਲਈ ਕਿਰਪਾ ਕਰਕੇ ਆਪਣਾ ਈਮੇਲ ਦਰਜ ਕਰੋ।',
      'snackForgotInvalidEmail': 'ਕਿਰਪਾ ਕਰਕੇ ਵੈਧ ਈਮੇਲ ਐਡਰੈੱਸ ਦਰਜ ਕਰੋ।',
      'signupTitle': 'ਸਾਈਨ ਅੱਪ',
      'fullNameLabel': 'ਪੂਰਾ ਨਾਮ',
      'usernameLabel': 'ਯੂਜ਼ਰਨਾਮ',
      'usernameHint': 'ਇੱਕ ਵਿਲੱਖਣ ਯੂਜ਼ਰਨਾਮ ਚੁਣੋ',
      'usernameRequired': 'ਯੂਜ਼ਰਨਾਮ ਲਾਜ਼ਮੀ ਹੈ',
      'usernameInvalid':
          '3-20 ਅੱਖਰ, ਅੰਕ, ਡਾਟ, ਅੰਡਰਸਕੋਰ ਜਾਂ ਹਾਈਫਨ ਵਰਤੋ',
      'nameRequired': 'ਨਾਮ ਲਾਜ਼ਮੀ ਹੈ',
      'emailAddressLabel': 'ਈਮੇਲ ਐਡਰੈੱਸ',
      'emailRequired': 'ਈਮੇਲ ਲਾਜ਼ਮੀ ਹੈ',
      'emailInvalid': 'ਗਲਤ ਈਮੇਲ',
      'countryCodeLabel': 'ਦੇਸ਼ ਕੋਡ',
      'phoneNumberLabel': 'ਫੋਨ ਨੰਬਰ',
      'phoneNumberHint': '',
      'phoneRequired': 'ਫੋਨ ਨੰਬਰ ਲਾਜ਼ਮੀ ਹੈ',
      'phoneInvalid': 'ਕਿਰਪਾ ਕਰਕੇ ਵੈਧ ਫੋਨ ਨੰਬਰ ਦਰਜ ਕਰੋ',
      'languageLabel': 'ਪਸੰਦੀਦਾ ਭਾਸ਼ਾ',
      'passwordRequired': 'ਪਾਸਵਰਡ ਲਾਜ਼ਮੀ ਹੈ',
      'passwordMinLength': 'ਘੱਟੋ-ਘੱਟ 6 ਅੱਖਰ',
      'confirmPasswordLabel': 'ਪਾਸਵਰਡ ਦੀ ਪੁਸ਼ਟੀ ਕਰੋ',
      'confirmPasswordRequired': 'ਕਿਰਪਾ ਕਰਕੇ ਪਾਸਵਰਡ ਦੀ ਪੁਸ਼ਟੀ ਕਰੋ',
      'confirmPasswordMismatch': 'ਪਾਸਵਰਡ ਮੇਲ ਨਹੀਂ ਖਾਂਦੇ',
      'termsAgreement':
      'ਕਿਰਪਾ ਕਰਕੇ ਜਾਰੀ ਰੱਖਣ ਲਈ ਸ਼ਰਤਾਂ ਨਾਲ ਸਹਿਮਤ ਹੋਵੋ।',
      'userAgreementTitle': 'ਨਿਯਮ ਅਤੇ ਸ਼ਰਤਾਂ ਅਤੇ ਗੋਪਨੀਯਤਾ ਨੀਤੀ',
      'userAgreementContent':
      'ਇਹ ਨਿਯਮ ਅਤੇ ਸ਼ਰਤਾਂ ਅਤੇ ਗੋਪਨੀਯਤਾ ਨੀਤੀ ਲਈ ਪਲੇਸਹੋਲਡਰ ਹੈ। ਅਸਲੀ ਐਪ ਵਿੱਚ ਤੁਸੀਂ ਪੂਰਾ ਪਾਠ ਦਿਖਾਓਗੇ ਜਾਂ ਵੈੱਬਵਿਊ ਖੋਲ੍ਹੋਗੇ।',
      'close': 'ਬੰਦ ਕਰੋ',
      'agreeTextPrefix': 'ਮੈਂ ਪੜ੍ਹਿਆ ਹੈ ਅਤੇ ਸਹਿਮਤ ਹਾਂ ',
      'userAgreement': 'ਨਿਯਮ ਅਤੇ ਸ਼ਰਤਾਂ',
      'and': ' ਅਤੇ ',
      'privacyPolicy': 'ਗੋਪਨੀਯਤਾ ਨੀਤੀ',
      'searchCountryCodes': 'ਦੇਸ਼ ਕੋਡ ਖੋਜੋ',
      'noCountryCodeResults': 'ਤੁਹਾਡੇ ਖੋਜ ਨਾਲ ਕੋਈ ਦੇਸ਼ ਨਹੀਂ ਮਿਲਿਆ।',
      'policyLoadFailed': 'ਸਮੱਗਰੀ ਲੋਡ ਨਹੀਂ ਹੋ ਸਕੀ। ਕਿਰਪਾ ਕਰਕੇ ਮੁੜ ਕੋਸ਼ਿਸ਼ ਕਰੋ।',
      'policyRetryButton': 'ਮੁੜ ਕੋਸ਼ਿਸ਼ ਕਰੋ',
      'policyLastUpdatedLabel': 'ਆਖਰੀ ਵਾਰ ਅੱਪਡੇਟ',
      'signupButton': 'ਸਾਈਨ ਅੱਪ',
      'alreadyAccountPrompt': 'ਕੀ ਪਹਿਲਾਂ ਹੀ ਖਾਤਾ ਹੈ? ',
      'loginAction': 'ਲਾਗਇਨ',
      'createPasswordTitle': 'ਨਵਾਂ ਪਾਸਵਰਡ ਬਣਾਓ',
      'newPasswordLabel': 'ਨਵਾਂ ਪਾਸਵਰਡ',
      'newPasswordHint': 'ਨਵਾਂ ਪਾਸਵਰਡ ਦਰਜ ਕਰੋ',
      'confirmPasswordHint': 'ਪਾਸਵਰਡ ਦੀ ਪੁਸ਼ਟੀ ਕਰੋ',
      'passwordMinEight':
          'ਪਾਸਵਰਡ ਘੱਟੋ-ਘੱਟ 6 ਅੱਖਰਾਂ ਦਾ ਹੋਣਾ ਚਾਹੀਦਾ ਹੈ।',
      'passwordsDoNotMatch': 'ਪਾਸਵਰਡ ਮੇਲ ਨਹੀਂ ਖਾਂਦੇ।',
      'resetPasswordButton': 'ਪਾਸਵਰਡ ਰੀਸੈਟ ਕਰੋ',
      'verifyNumberTitle': 'ਆਪਣਾ ਈਮੇਲ ਤਸਦੀਕ ਕਰੋ',
      'verifyCodeDescription':
      'ਅਸੀਂ ਤੁਹਾਡੇ ਈਮੇਲ ਉੱਤੇ 6 ਅੰਕਾਂ ਦਾ ਕੋਡ ਭੇਜਿਆ ਹੈ।',
      'enterCodeLabel': 'ਕੋਡ ਦਰਜ ਕਰੋ',
      'verifyOtpButton': 'ਓਟੀਪੀ ਦੀ ਤਸਦੀਕ ਕਰੋ',
      'resendPromptQuestion': 'ਕੋਡ ਨਹੀਂ ਮਿਲਿਆ?',
      'resendCountdown': '00:{seconds} ਵਿੱਚ ਮੁੜ ਭੇਜੋ',
      'resendCode': 'ਕੋਡ ਮੁੜ ਭੇਜੋ',
      'operationSuccessful': 'ਕਾਰਵਾਈ ਸਫਲ ਰਹੀ',
    },
    'it': {
      'appTitle': 'PresenzePro',
      'drawerUserName': 'John Snow',
      'drawerUserPhone': '+39-319-055-5550',
      'dashboardLabel': 'Elenco lavori',
      'homeBannerTitle': 'Monitora le presenze in modo intelligente',
      'homeBannerSubtitle':
          'Gestisci i tuoi turni, traccia le ore e rimani organizzato ogni giorno.',
      'adPlaceholderTitle': 'Spazio pubblicitario in arrivo',
      'adPlaceholderSubtitle':
          'Presto mostreremo qui offerte rilevanti. Restate sintonizzati!',
      'addNewWorkLabel': 'Aggiungi nuovo lavoro',
      'selectWorkTitle': 'Seleziona lavoro',
      'workSelectionSubtitle':
          'Scegli il lavoro di cui vuoi visualizzare i report.',
      'confirmSelectionButton': 'Conferma selezione',
      'workSelectionHourSuffix': '/ora',
      'attendanceHistoryLabel': 'Storico presenze',
      'attendanceHistoryMonthLabel': 'Seleziona mese',
      'attendanceHistorySummaryTitle': 'Questo mese finora',
      'attendanceHistoryWorkedDaysLabel': 'Giorni lavorati',
      'attendanceHistoryLeaveDaysLabel': 'Giorni di permesso',
      'attendanceHistoryOvertimeLabel': 'Straordinari',
      'attendanceHistoryTimelineTitle': 'Cronologia giornaliera',
      'attendanceHistoryNoEntriesLabel': 'Nessuna registrazione di presenza.',
      'attendanceHistoryLoadFailedMessage':
          'Impossibile caricare lo storico presenze. Riprova.',
      'attendanceHistoryHourlyEntry': 'Orario',
      'attendanceHistoryContractEntry': 'Contratto',
      'attendanceHistoryLeaveEntry': 'Permesso',
      'attendanceHistoryPendingTitle': 'Registrazioni di presenza in sospeso',
      'attendanceHistoryPendingDescription':
          'Completa i giorni precedenti prima di segnare oggi come presente.',
      'attendanceHistoryResolveButton': 'Completa ora',
      'attendanceHistoryAllCaughtUp': 'Sei completamente aggiornato!',
      'attendanceHistoryAllCaughtUpDescription':
          'Tutte le presenze precedenti sono completate.',
      'attendanceHistoryAllWorks': 'Tutti i lavori',
      'attendanceHistoryOvertimeEntryLabel': 'Straordinari',
      'attendanceHistoryLoggedHoursLabel': 'Ore registrate',
      'attendanceHistoryReasonLabel': 'Motivo',
      'contractReportDownloadLabel': 'Scarica rapporto contratti (PDF)',
      'historyReportDownloadLabel': 'Scarica storico presenze (PDF)',
      'reportDownloadNoEntriesMessage':
          'Nessun record disponibile per la vista selezionata.',
      'reportDownloadSuccessMessage': 'PDF salvato in {path}',
      'reportDownloadFailedMessage':
          'Impossibile generare il report PDF. Riprova.',
      'contractWorkLabel': 'Lavoro a contratto',
      'contractWorkActiveRatesTitle': 'Tariffe contratto attive',
      'contractWorkDefaultTypesTitle': 'Tipi di contratto',
      'contractWorkRecentEntriesTitle': 'Registrazioni contratto recenti',
      'contractWorkRatesNote': 'Le tariffe si applicano solo alle registrazioni future.',
      'contractWorkAddTypeTitle': 'Aggiungi tipo di contratto',
      'contractWorkEditTypeTitle': 'Aggiorna tipo di contratto',
      'contractWorkSetupSubtitle':
          'Seleziona i tipi di lavoro a contratto e imposta le tariffe',
      'contractWorkContractTypeLabel': 'Tipo di contratto',
      'contractWorkContractTypeHint': 'Seleziona il tipo di contratto',
      'contractWorkPricePerCrateLabel': 'Prezzo per cassa',
      'contractWorkSaveAllButton': 'Salva tutti i lavori a contratto',
      'contractWorkNameLabel': 'Nome contratto',
      'contractWorkSelectWorkHint': 'Seleziona lavoro',
      'contractWorkCustomOption': 'Lavoro personalizzato',
      'contractWorkRateLabel': 'Tariffa',
      'contractWorkRateHint': 'Inserisci la tariffa',
      'contractWorkPricePerBinHint': 'Prezzo per 1 cassone',
      'contractWorkPricePerCrateHint': 'Prezzo per 1 cassetta',
      'contractWorkPricePerBunchesHint': 'Prezzo per 100 mazzi',
      'contractWorkUnitLabel': 'Etichetta unità',
      'contractWorkSubtypeLabel': 'Tipo',
      'contractWorkSubtypeHint': 'Seleziona tipo',
      'contractWorkSubtypeCustomOption': 'Sottotipo personalizzato',
      'contractWorkSubtypeCustomLabel': 'Sottotipo personalizzato',
      'contractWorkSubtypeRequiredMessage': 'Seleziona un tipo.',
      'contractWorkTypeLabel': 'Tipo',
      'contractWorkTypeHint': 'Seleziona tipo',
      'contractWorkTypeFixedOption': 'Fisso',
      'contractWorkTypeBundleOption': 'Pacchetto',
      'contractWorkRoleLabel': 'Ruolo',
      'contractWorkRoleHint': 'Seleziona ruolo',
      'contractWorkRoleRequiredMessage': 'Seleziona un ruolo.',
      'contractWorkUnitsLabel': 'Unità',
      'contractWorkUnitsHint': 'Inserisci le unità',
      'contractWorkRateRequiredMessage': 'Inserisci una tariffa valida.',
      'contractWorkNameRequiredMessage':
          'Seleziona o inserisci il nome del lavoro.',
      'contractWorkTypeSavedMessage': 'Tipo di contratto salvato.',
      'contractWorkDeleteConfirmationTitle': 'Elimina tipo di contratto',
      'contractWorkDeleteConfirmationMessage':
          'Sei sicuro di voler eliminare questo tipo di contratto?',
      'contractWorkDeleteButton': 'Elimina',
      'contractWorkTypeDeletedMessage': 'Tipo di contratto eliminato.',
      'contractWorkTypeDeleteFailedMessage':
          'Impossibile eliminare il tipo di contratto. Riprova.',
      'contractWorkNoEntriesLabel': 'Nessuna registrazione contratto.',
      'contractWorkAllTypesAddedMessage':
          'Tutti i tipi di lavoro a contratto sono già stati aggiunti.',
      'contractWorkLastUpdatedLabel': 'Ultimo aggiornamento',
      'contractWorkEditRateButton': 'Aggiorna tariffa',
      'contractWorkActiveTypesLabel': 'Tipi attivi',
      'contractWorkTotalUnitsLabel': 'Unità totali',
      'contractWorkTotalSalaryLabel': 'Salario totale',
      'contractWorkDefaultTag': 'Predefinito',
      'contractWorkUnitFallback': 'per unità',
      'contractWorkCloseSheetLabel': 'Chiudi dettagli tipo contratto',
      'profileLabel': 'Profilo',
      'profileTitle': 'Modifica profilo',
      'profileNameLabel': 'Nome completo',
      'profileNameHint': 'Inserisci il tuo nome',
      'profileUsernameLabel': 'Nome utente',
      'profileUsernameHint': 'Inserisci il tuo nome utente',
      'profilePhoneLabel': 'Numero di telefono',
      'profilePhoneHint': 'Inserisci il tuo numero di telefono',
      'profileCountryCodeLabel': 'Prefisso internazionale',
      'profileCountryCodeHint': 'Inserisci il prefisso (es. +39)',
      'profileLanguageLabel': 'Lingua preferita',
      'profileSaveButton': 'Salva modifiche',
      'profileUpdateSuccess': 'Profilo aggiornato con successo.',
      'profileUpdateFailed': 'Impossibile aggiornare il profilo. Riprova.',
      'profileAuthRequired': 'Accedi nuovamente per aggiornare il profilo.',
      'profileValidationName': 'Inserisci il tuo nome.',
      'profileValidationUsername': 'Inserisci il tuo nome utente.',
      'profileValidationPhone': 'Inserisci il tuo numero di telefono.',
      'profileValidationCountryCode': 'Inserisci il prefisso internazionale.',
      'profileValidationLanguage': 'Seleziona una lingua.',
      'profileLoadingFailed': 'Impossibile caricare i dettagli del profilo.',
      'contractWorkCustomTypesTitle': 'I tuoi tipi di contratto',
      'contractWorkNoCustomTypesLabel':
          'Nessun tipo di contratto aggiunto. Aggiungi un nuovo contratto nei dettagli del lavoro.',
      'contractWorkLoadError': 'Impossibile caricare i tipi di contratto in questo momento.',
      'changeLanguageLabel': 'Cambia lingua',
      'helpSupportLabel': 'Assistenza',
      'helpSupportTitle': 'Come possiamo aiutarti oggi?',
      'helpSupportSubtitle':
          'Trova risposte rapide o contatta il nostro team di supporto.',
      'helpSupportQuickActionsTitle': 'Assistenza rapida',
      'helpSupportFaqsLabel': 'Domande frequenti',
      'helpSupportFaqsSubtitle': 'Consulta le domande comuni',
      'helpSupportGuidesLabel': 'Guida introduttiva',
      'helpSupportGuidesSubtitle': 'Tutorial passo dopo passo',
      'helpSupportReportIssueLabel': 'Segnala un problema',
      'helpSupportReportIssueSubtitle': 'Facci sapere cosa è successo',
      'helpSupportContactTitle': 'Opzioni di contatto',
      'helpSupportEmailLabel': 'Scrivici',
      'helpSupportEmailValue': 'support@attendancepro.app',
      'helpSupportEmailButton': 'Invia email',
      'helpSupportPhoneLabel': 'Chiamaci',
      'helpSupportPhoneValue': '+91 9876543210',
      'helpSupportCallButton': 'Chiama ora',
      'helpSupportChatLabel': 'Chat live',
      'helpSupportChatSubtitle': 'Disponibile Lun-Ven, 9:00 - 18:00',
      'helpSupportChatButton': 'Avvia chat',
      'helpSupportHoursLabel': 'Orari di supporto',
      'helpSupportHoursValue': 'Lun - Ven, 9:00 - 18:00 (GMT)',
      'helpSupportResponseTimeLabel': 'Tempo medio di risposta',
      'helpSupportResponseTimeValue': 'Entro 24 ore',
      'helpSupportAdditionalInfoTitle': 'Informazioni aggiuntive',
      'helpSupportLastUpdatedLabel': 'Ultimo aggiornamento',
      'helpSupportLastUpdatedValue': 'Ottobre 2025',
      'helpSupportPolicyLabel': 'Politica di supporto',
      'helpSupportPolicyValue':
          'Seguiamo gli standard di assistenza clienti di AttendancePro.',
      'helpSupportLaunchFailed':
          'Impossibile aprire l\'applicazione richiesta.',
      'helpSupportComingSoon': 'Questa sezione sarà disponibile a breve.',
      'deleteAccountLabel': 'Elimina account',
      'logoutLabel': 'Esci',
      'reportsSummaryLabel': 'Report e riepilogo',
      'reportsSummaryMonth': 'October 2025',
      'reportsCombinedSalaryTitle': 'Total Combined Salary',
      'reportsHoursWorkedSuffix': 'hours worked',
      'reportsUnitsCompletedSuffix': 'units completed',
      'reportsHourlyWorkSummaryTitle': 'Hourly Work Summary',
      'reportsWorkingDaysLabel': 'Working Days',
      'reportsAverageHoursPerDayLabel': 'Average Hours/Day',
      'reportsLastPayoutLabel': 'Last Payout',
      'reportsTotalUnitsLabel': 'Total Units',
      'reportsContractSalaryLabel': 'Contract Salary',
      'reportsBreakdownSuffix': 'Breakdown',
      'reportsMonthlySectionTitle': 'Rapporto mensile',
      'reportsMonthlyTypeHourly': 'Orario',
      'reportsMonthlyTypeFixed': 'Stipendio fisso',
      'reportsMonthlyEmptyMessage':
          'Nessun record disponibile per questo mese.',
      'reportsGrandTotalLabel': 'Grand Total',
      'reportsLoadingMessage': 'Recupero del riepilogo più recente...',
      'dashboardSummaryLoadFailedMessage':
          'Impossibile caricare il riepilogo della dashboard. Riprova.',
      'reportsLoadFailedMessage': 'Impossibile caricare i report. Riprova.',
      'logoutConfirmationTitle': 'Conferma logout',
      'logoutConfirmationMessage': 'Sei sicuro di voler uscire?',
      'logoutConfirmButton': 'Esci',
      'logoutCancelButton': 'Annulla',
      'logoutSuccessMessage': 'Disconnessione avvenuta con successo.',
      'logoutFailedMessage': 'Impossibile disconnettersi. Riprova.',
      'deleteAccountConfirmationTitle': 'Elimina account',
      'deleteAccountConfirmationMessage':
          'Sei sicuro di voler eliminare il tuo account? Questa azione non può essere annullata.',
      'deleteAccountConfirmButton': 'Elimina',
      'deleteAccountCancelButton': 'Annulla',
      'deleteAccountSuccessMessage': 'Account eliminato con successo.',
      'deleteAccountFailedMessage': 'Impossibile eliminare l\'account. Riprova.',
      'shareAppTitle': 'Condividi app',
      'shareViaWhatsApp': 'Condividi via WhatsApp',
      'copyLink': 'Copia link',
      'shareCancelButton': 'Annulla',
      'shareLinkCopied': 'Link copiato negli appunti.',
      'shareWhatsappUnavailable': 'WhatsApp non è installato su questo dispositivo.',
      'shareWhatsappFailed': 'Impossibile aprire WhatsApp.',
      'shareMessage': 'Scopri AttendancePro: {link}',
      'dashboardTappedMessage': 'Dashboard selezionata',
      'addNewWorkTappedMessage': 'Nuovo lavoro selezionato',
      'attendanceHistoryTappedMessage': 'Storico presenze selezionato',
      'contractWorkTappedMessage': 'Lavoro a contratto selezionato',
      'helpSupportTappedMessage': 'Assistenza selezionata',
      'workA': 'Lavoro A',
      'workB': 'Lavoro B',
      'switchedToWorkA': 'Passato a Lavoro A',
      'switchedToWorkB': 'Passato a Lavoro B',
      'selectLanguageTitle': 'Seleziona lingua',
      'languageEnglish': 'Inglese',
      'languageHindi': 'Hindi',
      'languagePunjabi': 'Punjabi',
      'languageItalian': 'Italiano',
      'languageSelection': 'Lingua: {language}',
      'noWorkAddedYet': 'Nessun lavoro aggiunto',
      'startTrackingAttendance':
      'Inizia a registrare le presenze\naggiungendo il tuo primo lavoro',
      'addYourFirstWork': 'Aggiungi il tuo primo lavoro',
      'hourlyWorkLabel': 'Lavoro Orario',
      'changeWorkButton': 'Cambia lavoro',
      'todaysAttendanceTitle': 'Presenze di oggi',
      'startTimeLabel': 'Ora di inizio',
      'endTimeLabel': 'Ora di fine',
      'breakLabel': 'Tempo di pausa',
      'attendanceSubmitButton': 'Salva presenza',
      'attendanceStartTimeRequired': "L'orario di inizio è obbligatorio",
      'attendanceEndTimeRequired': "L'orario di fine è obbligatorio",
      'attendanceInvalidTimeFormat': 'Inserisci l\'orario nel formato HH:MM',
      'attendanceBreakInvalid': 'Inserisci la pausa in minuti',
      'attendanceUnitsRequired': 'Inserisci il numero di unità',
      'attendanceUnitsInvalid': 'Inserisci un numero di unità valido',
      'attendanceRateRequired': 'Inserisci la tariffa per unità',
      'attendanceRateInvalid': 'Inserisci una tariffa per unità valida',
      'attendanceSubmitSuccess': 'Presenza salvata con successo',
      'attendanceAlreadyMarkedMessage':
          'Presenza già registrata per oggi. Per apportare modifiche, usa l\'opzione Modifica.',
      'attendanceSubmitFailed': 'Impossibile salvare la presenza. Riprova.',
      'attendanceMissedEntriesTitle': 'Completa le presenze in sospeso',
      'attendanceMissedEntriesDescription':
          'Non hai registrato la presenza nelle seguenti date. Completa i giorni mancanti prima di aggiungere nuove presenze.',
      'attendanceMissedEntriesListLabel': 'Date in sospeso',
      'attendanceMissedEntriesReviewButton': 'Rivedi {date}',
      'attendanceMissedEntriesLoadFailed':
          'Impossibile verificare le presenze in sospeso. Riprova.',
      'attendanceMissedEntriesResolveButton': 'Risolvi ora',
      'attendanceMissedEntriesCompleteSuccess':
          'Presenze mancanti completate con successo.',
      'attendanceMissedEntriesCompleteFailed':
          'Impossibile completare le presenze mancanti. Riprova.',
      'attendancePreviewTitle': 'Conferma presenza',
      'attendancePreviewDescription':
          'Controlla i dettagli prima di salvare la registrazione di presenza.',
      'attendancePreviewConfirmButton': 'Conferma e salva',
      'attendancePreviewCancelButton': 'Modifica registrazione',
      'attendancePreviewHoursLabel': 'Ore calcolate',
      'attendancePreviewSalaryLabel': 'Salario calcolato',
      'attendancePreviewValidationPrompt': 'Queste ore sono corrette?',
      'attendancePreviewFetchFailed':
          'Impossibile mostrare l\'anteprima della presenza. Riprova.',
      'attendanceDateLabel': 'Data',
      'attendanceEntryTypeLabel': 'Tipo di registrazione',
      'submitButton': 'Invia',
      'markAsWorkOffButton': 'Segna come riposo',
      'contractWorkSummaryTitle': 'Riepilogo lavoro a contratto',
      'summaryLabel': 'Riepilogo',
      'totalHoursLabel': 'Ore totali',
      'totalSalaryLabel': 'Salario totale',
      'activeWorkLabel': 'Attivo',
      'setActiveWorkButton': 'Imposta come attivo',
      'settingActiveWorkLabel': 'Attivazione...',
      'workActivatedMessage': 'Lavoro impostato come attivo con successo.',
      'workActivatedWithNameMessage':
          'Il tuo lavoro {workName} è ora attivo.',
      'workNameLabel': 'Nome del Lavoro',
      'workNameHint': 'Es. Ristorante, Magazzino',
      'workNameTooShortValidation': 'Il nome del lavoro deve contenere almeno 3 caratteri.',
      'hourlySalaryLabel': 'Paga Oraria',
      'hourlySalaryHint': '€ 0,00',
      'hourlyRateNegativeValidation': 'La tariffa oraria non può essere negativa.',
      'contractWorkHeader': 'Lavoro a Contratto (se disponibile)',
      'contractHistoryButton': 'Cronologia contratti',
      'addContractWorkButton': 'Aggiungi Lavoro a Contratto',
      'contractWorkDescription':
          'Gestisci lavori a cottimo come Ravanello, Rapa, Carota oppure aggiungi i tuoi.',
      'cancelButton': 'Annulla',
      'saveButtonLabel': 'Salva',
      'saveWorkButton': 'Salva Lavoro',
      'saveChangesButton': 'Salva modifiche',
      'deleteWorkButton': 'Elimina lavoro',
      'workNameRequiredMessage': 'Inserisci il nome del lavoro.',
      'workAddedMessage': 'Lavoro aggiunto con successo.',
      'workUpdatedMessage': 'Lavoro aggiornato con successo.',
      'invalidHourlyRateMessage': 'Inserisci una tariffa oraria valida.',
      'editWorkTitle': 'Modifica lavoro',
      'editWorkSubtitle': 'Aggiorna i dettagli del lavoro',
      'editWorkDetailsTitle': 'Modifica i dettagli del lavoro',
      'editWorkDetailsSubtitle':
          'Aggiorna nome lavoro, tariffa oraria o impostazioni del contratto',
      'updateWorkButton': 'Aggiorna lavoro',
      'editWorkTooltip': 'Modifica lavoro',
      'workDeleteConfirmationTitle': 'Elimina lavoro',
      'workDeleteConfirmationMessage':
          'Sei sicuro di voler eliminare questo lavoro?',
      'workDeleteConfirmButton': 'Elimina',
      'workDeleteCancelButton': 'Annulla',
      'workDeleteIrreversibleMessage':
          'Eliminando questo lavoro rimuoverai in modo permanente tutte le presenze collegate.',
      'workDeleteSuccessMessage': 'Lavoro eliminato con successo.',
      'workDeleteFailedMessage':
          'Impossibile eliminare il lavoro. Riprova.',
      'workSaveFailedMessage': 'Impossibile salvare il lavoro. Riprova.',
      'worksLoadFailedTitle': 'Impossibile caricare i lavori',
      'worksLoadFailedMessage':
          'Non siamo riusciti a recuperare i tuoi lavori. Trascina verso il basso per aggiornare o riprova.',
      'retryButtonLabel': 'Riprova',
      'notAvailableLabel': 'Non disponibile',
      'authenticationRequiredMessage': 'La tua sessione è scaduta. Accedi di nuovo.',
      'walkthroughTitleOne': 'Traccia facilmente le ore di lavoro',
      'walkthroughDescOne':
      'Avvia e termina la giornata con un tocco. Tieni le ore precise e ordinate.',
      'walkthroughTitleTwo': "Più lavori, un'unica app",
      'walkthroughDescTwo':
      'Passa facilmente tra i lavori e vedi subito i tuoi guadagni.',
      'walkthroughTitleThree': 'La tua lingua, a modo tuo',
      'walkthroughDescThree':
      'Disponibile in inglese, hindi, punjabi e italiano così gestisci le presenze come preferisci.',
      'skip': 'Salta',
      'splashTitle': 'PresenzePro',
      'loginTitle': 'Accesso',
      'loginPhoneTab': 'Telefono',
      'loginEmailTab': 'Email',
      'loginIdentifierLabel': 'Email o numero di telefono',
      'loginIdentifierHint': 'you@example.com o 9876543210',
      'loginPhoneLabel': 'Numero di telefono',
      'loginPhoneHint': 'Numero di telefono',
      'loginEmailLabel': 'Indirizzo email',
      'loginEmailHint': 'Inserisci email',
      'emailLabel': 'Email',
      'emailHint': 'Inserisci email',
      'passwordLabel': 'Password',
      'passwordHint': '********',
      'loginButton': 'Accedi',
      'forgotPassword': 'Password dimenticata?',
      'forgotPasswordSubtitle':
          'Inserisci la tua email registrata per ricevere un codice di verifica.',
      'forgotPasswordFieldLabel': 'Indirizzo email',
      'forgotPasswordFieldHint': 'Inserisci email',
      'sendOtpButton': 'Invia OTP',
      'backToLogin': 'Torna al login',
      'signupPromptPrefix': 'Non hai un account? ',
      'signupPromptAction': 'Registrati',
      'changeLanguage': 'Cambia lingua',
      'snackEnterLoginIdentifier': 'Inserisci la tua email o il numero di telefono.',
      'snackEnterValidLoginIdentifier': 'Inserisci un indirizzo email o un numero di telefono valido.',
      'snackEnterPhone': 'Inserisci il tuo numero di telefono.',
      'snackEnterValidPhone': 'Inserisci un numero di telefono valido.',
      'snackEnterEmail': 'Inserisci la tua email.',
      'snackEnterValidEmail': 'Inserisci un indirizzo email valido.',
      'snackEnterPassword': 'Inserisci la tua password.',
      'snackLoginSuccess': 'Accesso eseguito correttamente',
      'snackResetEmail': 'Inserisci la tua email per reimpostare.',
      'snackForgotInvalidEmail': 'Inserisci un indirizzo email valido.',
      'signupTitle': 'Registrati',
      'fullNameLabel': 'Nome completo',
      'usernameLabel': 'Nome utente',
      'usernameHint': 'Scegli un nome utente univoco',
      'usernameRequired': 'Nome utente obbligatorio',
      'usernameInvalid':
          'Usa da 3 a 20 lettere, numeri, punti, underscore o trattini',
      'nameRequired': 'Nome obbligatorio',
      'emailAddressLabel': 'Indirizzo email',
      'emailRequired': 'Email obbligatoria',
      'emailInvalid': 'Email non valida',
      'countryCodeLabel': 'Prefisso internazionale',
      'phoneNumberLabel': 'Numero di telefono',
      'phoneNumberHint': '',
      'phoneRequired': 'Numero di telefono obbligatorio',
      'phoneInvalid': 'Inserisci un numero di telefono valido',
      'languageLabel': 'Lingua preferita',
      'passwordRequired': 'Password obbligatoria',
      'passwordMinLength': 'Minimo 6 caratteri',
      'confirmPasswordLabel': 'Conferma password',
      'confirmPasswordRequired': 'Conferma la password',
      'confirmPasswordMismatch': 'Le password non coincidono',
      'termsAgreement': 'Accetta i termini per continuare.',
      'userAgreementTitle': 'Termini e condizioni e informativa privacy',
      'userAgreementContent':
      "Questo è un testo fittizio per i Termini e condizioni e l'informativa privacy. Nell'app reale mostreresti il testo completo o apriresti una webview.",
      'close': 'Chiudi',
      'agreeTextPrefix': 'Ho letto e accetto ',
      'userAgreement': 'i Termini e condizioni',
      'and': ' e ',
      'privacyPolicy': "l'Informativa privacy",
      'searchCountryCodes': 'Cerca prefissi internazionali',
      'noCountryCodeResults': 'Nessun paese corrisponde alla tua ricerca.',
      'policyLoadFailed': 'Impossibile caricare il contenuto. Riprova.',
      'policyRetryButton': 'Riprova',
      'policyLastUpdatedLabel': 'Ultimo aggiornamento',
      'signupButton': 'Registrati',
      'alreadyAccountPrompt': 'Hai già un account? ',
      'loginAction': 'Accedi',
      'createPasswordTitle': 'Crea una nuova password',
      'newPasswordLabel': 'Nuova password',
      'newPasswordHint': 'Inserisci nuova password',
      'confirmPasswordHint': 'Conferma password',
      'passwordMinEight':
          'La password deve contenere almeno 6 caratteri.',
      'passwordsDoNotMatch': 'Le password non coincidono.',
      'resetPasswordButton': 'Reimposta password',
      'verifyNumberTitle': 'Verifica la tua email',
      'verifyCodeDescription':
      'Abbiamo inviato un codice di 6 cifre alla tua email.',
      'enterCodeLabel': 'Inserisci il codice',
      'verifyOtpButton': 'Verifica codice',
      'resendPromptQuestion': 'Non hai ricevuto il codice?',
      'resendCountdown': 'Invia di nuovo tra 00:{seconds}',
      'resendCode': 'Invia di nuovo',
      'operationSuccessful': 'Operazione riuscita',
    },
  }
;

  static String getLocaleValue(String languageCode, String key) {
    final localeValues = localizedValues[languageCode];
    if (localeValues != null && localeValues.containsKey(key)) {
      return localeValues[key]!;
    }
    final englishValues = localizedValues['en'];
    if (englishValues != null && englishValues.containsKey(key)) {
      return englishValues[key]!;
    }
    return key;
  }
}
